import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {parseFeed,contentHash,officialURL} from '../src/server/parsing';import {ruleEvaluation} from '../src/server/evaluation';import {berlinClock,runMonitor,dashboard,history} from '../src/server/monitor';import {resetDBForTests} from '../src/server/db';import type {DocumentInput,Source} from '../src/model';
const doc:DocumentInput={externalId:'1',title:'Exportkontrolle: Dual-Use',url:'https://www.bundestag.de/test',text:'Ein Entwurf zur Exportkontrolle liegt vor.',publishedAt:null,procedure:null,documentType:'RSS-Meldung'};
test('RSS removes executable markup and preserves explicit dates',()=>{const r=parseFeed('<rss><channel><item><title>Dual-Use</title><link>https://www.bundestag.de/test</link><description><![CDATA[<b>Exportkontrolle</b>]]></description><pubDate>Mon, 07 Sep 2026 08:00:00 GMT</pubDate></item></channel></rss>',doc.url);assert.equal(r[0].text,'Exportkontrolle');assert.equal(r[0].publishedAt,'2026-09-07T08:00:00.000Z');});
test('Atom handles alternate links and absent publication dates honestly',()=>{const r=parseFeed('<feed><entry><id>abc</id><title>A</title><link rel="self" href="https://www.bundestag.de/meta"/><link rel="alternate" href="https://www.bundestag.de/a"/><updated>2026-09-07</updated></entry></feed>',doc.url);assert.equal(r[0].url,'https://www.bundestag.de/a');assert.equal(r[0].publishedAt,null);});
test('Rejects HTML responses and XML entities',()=>{assert.throws(()=>parseFeed('<html>error</html>',doc.url));assert.throws(()=>parseFeed('<!DOCTYPE x><rss><channel/></rss>',doc.url));});
test('URL allowlist blocks private addresses, credentials and lookalike domains',()=>{assert.equal(officialURL('https://www.bundestag.de/a'),true);for(const s of ['http://www.bundestag.de','https://bundestag.de.attacker.com','https://localhost/','https://127.0.0.1/','https://me@www.bundestag.de/a'])assert.equal(officialURL(s),false);});
test('Metadata changes produce a new hash; whitespace does not',()=>{assert.equal(contentHash(doc),contentHash({...doc,text:'Ein  Entwurf zur Exportkontrolle liegt vor.'}));assert.notEqual(contentHash(doc),contentHash({...doc,procedure:'Abgeschlossen'}));});
test('Keyword hit never fabricates ownership, deadline or proven relevance',()=>{const r=ruleEvaluation(doc);assert.equal(r.category,'watch');assert.equal(r.owner,'Nicht im Text enthalten');assert.equal(r.window,'Nicht im Text enthalten');assert.ok(r.channels.includes('K2'));assert.equal(ruleEvaluation({...doc,title:'Sport',text:'Ein Fußballturnier.'}).category,'irrelevant');});
test('06:00 Berlin handles summer and winter offsets',()=>{assert.equal(berlinClock(new Date('2026-07-10T04:00:00Z')).hour,6);assert.equal(berlinClock(new Date('2026-01-10T05:00:00Z')).hour,6);assert.equal(berlinClock(new Date('2026-07-10T05:00:00Z')).hour,7);});
test('Persistent runs distinguish baseline, unchanged, new, changed and source failure',async()=>{const dir=mkdtempSync(join(tmpdir(),'policy-test-'));process.env.DATABASE_URL='file:'+join(dir,'test.db');delete process.env.OPENAI_API_KEY;const source:Source={id:'test',name:'Test',institution:'Test',url:doc.url,kind:'rss',feed:doc.url,note:'Fixture'};try{
 const first=await runMonitor({sources:[source],fetcher:async()=>[doc]});assert.equal(first?.items[0].change,'baseline');
 const second=await runMonitor({sources:[source],fetcher:async()=>[doc]});assert.equal(second?.items.length,0);
 const third=await runMonitor({sources:[source],fetcher:async()=>[{...doc,procedure:'Neu beraten'},{...doc,externalId:'2',title:'Forschung'}]});assert.equal(third?.items.find(i=>i.externalId==='1')?.change,'changed');assert.equal(third?.items.find(i=>i.externalId==='2')?.change,'new');
 const d=await dashboard();const h=await history(d.items.find(i=>i.externalId==='1')!.id);assert.equal(h.versions.length,2);assert.ok(h.diff.some(p=>p.added));
 const failure=await runMonitor({sources:[source],fetcher:async()=>{throw new Error('offline');}});assert.equal(failure?.coverage.failed,1);assert.match(failure!.summary,/Keine belastbare Aussage/);assert.equal((await dashboard()).items.length,2);
 assert.equal((await dashboard()).briefings.find(b=>b.id===first!.id)?.items[0].version,1);
 }finally{await resetDBForTests();delete process.env.DATABASE_URL;rmSync(dir,{recursive:true,force:true});}});
