import Head from 'next/head';
import {useEffect,useRef,useState} from 'react';
import {Radar,LayoutDashboard,FileText,Radio,Settings,Search,ArrowUpRight,RefreshCw,ChevronRight,Clock,ShieldCheck,AlertCircle,ArrowLeft,Download,Archive,History,Check,SlidersHorizontal,X,Landmark,FileDown,Building2,Target,Quote,CalendarDays,Users,Euro} from 'lucide-react';
import {COMMITTEES,MINISTRIES,SOURCES,committeeById,type Dashboard,type Item,type Briefing,type Change} from '../src/model';
import {TOPICS,topicById,type TopicMatch} from '../src/server/topics';
import type {LobbyProject} from '../src/server/lobby';
const HOSTED=process.env.NEXT_PUBLIC_HOSTED==='1';
// Statischer Betrieb auf GitHub Pages: kein Server, kein Schlüssel. Die Seite liest den Stand,
// den der tägliche Lauf in bootstrap.json geschrieben hat. Alles, was einen Server braucht, entfällt.
const STATIC=process.env.NEXT_PUBLIC_STATIC==='1';
const REPO=process.env.NEXT_PUBLIC_REPO??'';
const labels:Record<string,string>={baseline:'Ausgangsstand',new:'Neu',changed:'Geändert',unchanged:'Unverändert'};
const ministryById=(id:string)=>MINISTRIES.find(m=>m.id===id);
const empty:Dashboard={items:[],sources:SOURCES,briefings:[],events:[],lobby:[],serverTime:'',scheduleEnabled:false};
const date=(s:string|null|undefined,full=false)=>s?new Intl.DateTimeFormat('de-DE',full?{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s)):'Kein Datum in der Quelle';
// Nach welchem Datum die Liste ordnet: der Zeitpunkt der letzten Bewegung laut Quelle. Das eigene
// changedAt taugt dafuer nicht - beim Lauf bekommen alle Treffer denselben Zeitstempel, die
// Reihenfolge waere praktisch zufaellig. Ohne Quellendatum zaehlt der Erstkontakt, nicht "jetzt",
// sonst stehen datumslose Meldungen dauerhaft oben.
const recency=(i:Item)=>i.updatedAt??i.publishedAt??i.firstSeen;
const today=()=>new Date().toISOString().slice(0,10);
const isUpcoming=(i:Item)=>!!i.publishedAt&&i.publishedAt.slice(0,10)>=today()&&(i.documentType==='Ausschusstermin'||i.documentType==='Tagesordnung');
// Altbestand aus einem Stand vor der Themensuche traegt das Feld noch nicht.
const topicsOf=(i:Item):TopicMatch[]=>i.topics??[];
const bodies=(i:Item)=>[...i.committees.map(c=>committeeById(c)?.short),...i.ministries.map(m=>ministryById(m)?.short)].filter(Boolean) as string[];
const nav=[['overview','Lagebild',LayoutDashboard],['lobby','Akteure',Users],['committees','Ausschüsse',Landmark],['briefings','Briefings',FileText],['sources','Quellen',Radio],['settings','Einstellungen',Settings]] as const;
type Connection={url:string;token:string};
async function request<T>(conn:Connection,path:string,method='GET',body?:unknown):Promise<T>{
 if(!HOSTED&&!conn.token)throw new Error('Bitte unter Einstellungen den Verbindungsschlüssel hinterlegen.');
 const url=(HOSTED?'':conn.url.replace(/\/$/,''))+'/api/'+path;
 const headers:Record<string,string>={'Content-Type':'application/json'};if(!HOSTED)headers.Authorization='Bearer '+conn.token;
 const r=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(300000)});if(!r.headers.get('content-type')?.includes('application/json'))throw new Error('Bitte erneut mit ChatGPT anmelden. Dein gespeicherter Stand bleibt erhalten.');const data=await r.json() as T & {error?:string};if(!r.ok)throw new Error(data.error??'Verbindung fehlgeschlagen');return data;
}
export default function Home(){
 const [data,setData]=useState<Dashboard>(empty),[view,setView]=useState('overview'),[selected,setSelected]=useState<Item|null>(null);
 const [gremium,setGremium]=useState<string|null>(null),[topic,setTopic]=useState(''),[alleTreffer,setAlleTreffer]=useState(false),[query,setQuery]=useState(''),[source,setSource]=useState(''),[body,setBody]=useState(''),[after,setAfter]=useState(''),[status,setStatus]=useState<Change|''>(''),[docType,setDocType]=useState(''),[showArchive,setShowArchive]=useState(false),[filters,setFilters]=useState(false);
 const [conn,setConn]=useState<Connection>({url:'',token:''}),[draft,setDraft]=useState<Connection>({url:'',token:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[online,setOnline]=useState(false),[ready,setReady]=useState(false);
 const [pickedBriefing,setPickedBriefing]=useState<string>(''),[versions,setVersions]=useState<{versions:Item[];diff:{added?:boolean;removed?:boolean;value:string}[]}|null>(null),[tab,setTab]=useState('detail');
 const mainRef=useRef<HTMLElement>(null);
 async function loadSnapshot(){const r=await fetch(new URL('bootstrap.json',window.location.href).href,{cache:'no-store'});if(!r.ok)throw new Error('Stand nicht erreichbar');return await r.json() as Dashboard;}
 async function reload(){setBusy(true);setError('');try{setData(await loadSnapshot());setOnline(true);setNotice('Stand neu geladen.');}catch{setOnline(false);setError('Der gespeicherte Stand konnte nicht geladen werden. Bitte Internetverbindung prüfen.');}finally{setBusy(false);}}
 const cache=(d:Dashboard)=>{setData(d);try{localStorage.setItem('policy-cache',JSON.stringify(d));}catch{}};
 async function refresh(c=conn){setError('');try{const d=await request<Dashboard>(c,'dashboard');cache(d);setOnline(true);return true;}catch(e){setOnline(false);setError(e instanceof Error&&/timed? ?out|timeout|network|fetch/i.test(e.message)?'Die Verbindung dauert zu lange. Bitte Internetverbindung prüfen und erneut versuchen. Dein gespeicherter Stand bleibt erhalten.':e instanceof Error?e.message:'Keine Verbindung. Dein gespeicherter Stand bleibt erhalten.');return false;}}
 useEffect(()=>{let active=true;(async()=>{
 if(STATIC){try{const d=await loadSnapshot();if(active){setData(d);setOnline(true);}}catch{if(active)setError('Der gespeicherte Stand konnte nicht geladen werden. Bitte Seite neu laden.');}finally{if(active)setReady(true);}return;}
 let saved:Connection={url:'',token:''};try{saved=JSON.parse(localStorage.getItem('policy-connection')??'null')??saved;const cached=JSON.parse(localStorage.getItem('policy-cache')??'null');if(cached)setData(cached);}catch{}
 if(!HOSTED&&!saved.token){try{const r=await fetch('/connection.json');if(r.ok)saved=await r.json();}catch{}}
 try{if(!HOSTED&&!localStorage.getItem('policy-cache')){const r=await fetch('/bootstrap.json');if(r.ok&&active)setData(await r.json());}}catch{}
 if(!active)return;setConn(saved);setDraft(saved);setReady(true);if(saved.token||HOSTED)await refresh(saved);
 })();return()=>{active=false;};},[]);
 useEffect(()=>{if(selected){setTab('detail');setVersions(null);mainRef.current?.scrollTo(0,0);} },[selected?.id]);
 useEffect(()=>{if(!ready)return;const onVisible=()=>{if(document.visibilityState==='visible'&&(HOSTED||conn.token))void refresh();};document.addEventListener('visibilitychange',onVisible);return()=>document.removeEventListener('visibilitychange',onVisible);},[ready,conn.url,conn.token]);
 const latest=data.briefings[0];
 // Bei stuendlichen Laeufen wird nicht jedes Mal ein Briefing gespeichert. Der ehrliche Zeitpunkt
 // des letzten Abrufs steht deshalb im Quellenstatus, nicht im Briefing.
 const lastCheck=data.sources.map(s=>s.checkedAt).filter(Boolean).sort().at(-1);
 const lobby=(data.lobby??[]).filter(e=>!topic||e.topics.includes(topic));
 // Das Register meldet Spannen in Zehntausenderschritten. Ohne Nachkommastellen fallen Unter- und
 // Obergrenze in der kompakten Schreibweise zusammen ("6 Mio.–6 Mio.").
 const geld=(e:{spendFrom:number|null;spendTo:number|null})=>{
  if(e.spendFrom===null)return null;
  const f=(n:number)=>new Intl.NumberFormat('de-DE',{notation:'compact',maximumFractionDigits:n>=1e6?2:0}).format(n);
  const von=f(e.spendFrom),bis=f(e.spendTo??e.spendFrom);
  return (von===bis?von:`${von}–${bis}`)+' €';
 };
 const briefing=data.briefings.find(b=>b.id===pickedBriefing)??latest;
 const types=[...new Set(data.items.map(i=>i.documentType))].sort();
 const inTopic=(i:Item)=>!topic||topicsOf(i).some(m=>m.topic===topic);
 const matches=data.items.filter(i=>i.archived===showArchive&&inTopic(i)&&(!source||i.sourceId===source)&&(!body||i.committees.includes(body)||i.ministries.includes(body))&&(!status||i.change===status)&&(!docType||i.documentType===docType)&&(!after||!!i.publishedAt&&i.publishedAt.slice(0,10)>=after)&&(!query||(i.title+' '+i.documentNumber+' '+i.documentType+' '+bodies(i).join(' ')).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>recency(b).localeCompare(recency(a)));
 const counts=(c:Change)=>data.items.filter(i=>!i.archived&&i.change===c).length;
 const upcoming=data.items.filter(i=>!i.archived&&isUpcoming(i)).sort((a,b)=>a.publishedAt!.localeCompare(b.publishedAt!));
 const relevant=data.items.filter(i=>!i.archived&&topicsOf(i).length).sort((a,b)=>recency(b).localeCompare(recency(a)));
 const topicCount=(id:string)=>data.items.filter(i=>!i.archived&&topicsOf(i).some(m=>m.topic===id)).length;
 const shown=topic?relevant.filter(inTopic):relevant;
 const activeIn=(id:string)=>data.items.filter(i=>!i.archived&&(i.committees.includes(id)||i.ministries.includes(id)));
 async function run(){setBusy(true);setError('');setNotice('Quellen werden geprüft …');try{const r=await request<{briefing:Briefing}>(conn,'run','POST');await refresh();setNotice(r.briefing.summary);}catch(e){setNotice('');setError(e instanceof Error?e.message:'Quellenlauf fehlgeschlagen.');}finally{setBusy(false);}}
 function navigate(to:string){setSelected(null);setGremium(null);setView(to);setNotice('');mainRef.current?.scrollTo(0,0);}
 // Ein Klick auf ein Gremium oeffnet dessen eigene Liste, statt gefiltert auf die Startseite zu springen.
 function openBody(id:string){setGremium(id);setSelected(null);mainRef.current?.scrollTo(0,0);}
 const gremiumItems=gremium?data.items.filter(i=>!i.archived&&(i.committees.includes(gremium)||i.ministries.includes(gremium))).sort((a,b)=>recency(b).localeCompare(recency(a))):[];
 const gremiumInfo=gremium?committeeById(gremium)??ministryById(gremium):undefined;
 async function saveConnection(){try{const u=new URL(draft.url||window.location.origin);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw new Error('Bitte eine gültige Server-Adresse eingeben.');const next={url:u.origin,token:draft.token.trim()};if(!next.token)throw new Error('Verbindungsschlüssel fehlt.');setBusy(true);if(await refresh(next)){localStorage.setItem('policy-connection',JSON.stringify(next));setConn(next);setNotice('Verbindung gespeichert.');}}catch(e){setError(e instanceof Error?e.message:'Verbindung ungültig.');}finally{setBusy(false);}}
 async function exportBriefing(b:Briefing){
 const entry=(i:Item)=>[i.title,`${labels[i.change]} · ${i.documentType}${i.step?' · '+i.step:''}${i.documentNumber?' · Drucksache '+i.documentNumber:''}`,`Datum: ${date(i.publishedAt)}`,i.lead?`Federführend: ${committeeById(i.lead)?.name}`:'',bodies(i).length?`Gremien: ${bodies(i).join(', ')}`:'',i.originator?`Urheber: ${i.originator}`:'',`Quelle: ${i.url}`,i.pdfUrl?`PDF: ${i.pdfUrl}`:''].filter(Boolean).join('\n');
 const groups=[...new Set(b.items.flatMap(i=>[...i.committees,...i.ministries]))];
 const text=['POLICY MONITOR · TRUMPF · Ausgewählte Ausschüsse und Ressorts',date(b.createdAt,true),b.summary,
 ...groups.flatMap(g=>['\n'+(committeeById(g)?.name??ministryById(g)?.name??g),...b.items.filter(i=>i.committees.includes(g)||i.ministries.includes(g)).map(entry)]),
 ...(b.items.some(i=>!i.committees.length&&!i.ministries.length)?['\nOhne Gremienzuordnung',...b.items.filter(i=>!i.committees.length&&!i.ministries.length).map(entry)]:[])].join('\n\n');
 try{if(navigator.share){await navigator.share({title:'Policy Briefing '+b.day,text});}else{const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`Briefing-${b.day}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(e){if((e as Error).name!=='AbortError')setError('Export fehlgeschlagen.');}}
 async function toggleArchive(item:Item){setBusy(true);try{await request(conn,'items/'+item.id,'PATCH',{archived:!item.archived});await refresh();setSelected({...item,archived:!item.archived});setNotice(item.archived?'Dokument wiederhergestellt.':'Dokument archiviert.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function loadHistory(){setTab('history');try{setVersions(await request(conn,'history/'+selected!.id));}catch(e){setError((e as Error).message);}}
 const lead=selected?.lead?committeeById(selected.lead):undefined;
 return <><Head><title>Policy Monitor · TRUMPF</title><meta name="description" content="Neue Dokumente aus ausgewählten Bundestagsausschüssen und Ressorts"/><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/><meta name="theme-color" content="#173fe2"/><link rel="icon" href="icon.svg" type="image/svg+xml"/><link rel="apple-touch-icon" href="icon-180.png"/><link rel="manifest" href="manifest.webmanifest"/><meta name="apple-mobile-web-app-title" content="Policy Monitor"/><meta name="apple-mobile-web-app-capable" content="yes"/></Head>
 <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brandmark"><Radar size={27}/></div><div><strong>TRUMPF</strong><span>PUBLIC POLICY</span></div></div><div className="workspace">MONITORING WORKSPACE</div><nav aria-label="Hauptnavigation">{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>navigate(id)}><Icon size={20}/><span>{label}</span>{view===id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><ShieldCheck size={21}/><div><strong>Amtliche Quellen</strong><span>Anzeigen, nicht bewerten</span></div></div></aside>
 <main ref={mainRef} className="main"><header className="topbar"><div className="mobile-brand"><Radar size={22}/><b>TRUMPF</b><span>Policy Monitor</span></div><div className="breadcrumb">Public Policy <ChevronRight size={14}/> {nav.find(n=>n[0]===view)?.[1]}</div><div className={'connection '+(online?'connected':'')}><span/>{STATIC?(lastCheck?'Stand '+date(lastCheck,true):'Kein Stand geladen'):online?'Verbunden':data.items.length?'Gespeicherter Stand':'Noch nicht verbunden'}</div></header>
 <div className="content">{error&&<div className="notice error" role="alert"><AlertCircle size={19}/><span>{error}{HOSTED&&error.includes('anmelden')&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top"> Jetzt anmelden</a>}</span><button aria-label="Meldung schließen" onClick={()=>setError('')}><X size={17}/></button></div>}{notice&&<div className="notice" role="status"><Check size={19}/><span>{notice}</span></div>}
 {gremium&&!selected?<><button className="back" onClick={()=>setGremium(null)}><ArrowLeft size={18}/> Zurück zur Übersicht</button>
 <div className="detail-heading"><div className="eyebrow">{gremiumInfo&&'institution' in gremiumInfo?gremiumInfo.institution:'Ressort'}</div><h1>{gremiumInfo?.name}</h1><p className="muted">{gremiumInfo?.scope}</p></div>
 <section className="results"><div className="section-heading"><h2>Dokumente <span>{gremiumItems.length}</span></h2><span className="muted">Neueste zuerst · nur die letzten 10 Tage</span></div>
 {gremiumItems.length?<div className="item-list">{gremiumItems.map(i=><ItemCard key={i.id} item={i} onClick={()=>setSelected(i)}/>)}</div>:
 <div className="empty"><Landmark size={36}/><h3>Keine Dokumente im Zeitraum</h3><p>Aus diesem Gremium ist in den letzten 10 Tagen nichts eingegangen. Das ist eine Aussage über den Zeitraum, nicht über das Gremium.</p></div>}</section></>:
 selected?<><button className="back" onClick={()=>{setSelected(null);}}><ArrowLeft size={18}/> Zurück zur Übersicht</button><div className="detail-heading"><div className="eyebrow">{lead?lead.name:selected.institution} · {selected.documentType}</div><h1>{selected.title}</h1><div className="tags"><span className={'badge '+selected.change}>{labels[selected.change]}</span>{selected.documentNumber&&<span className="badge neutral">Drucksache {selected.documentNumber}</span>}{selected.step&&<span className="badge neutral">{selected.step}</span>}{selected.archived&&<span className="badge neutral">Archiviert</span>}</div></div><div className="detail-tabs"><button className={tab==='detail'?'active':''} onClick={()=>setTab('detail')}>Dokument & Quelle</button>{!STATIC&&<button className={tab==='history'?'active':''} onClick={loadHistory}>Versionen & Änderungen</button>}</div>
 {tab==='detail'?<div className="detail-grid"><section className="panel"><div className="eyebrow">DAS PAPIER</div><h2>{selected.documentType}{selected.step&&selected.step!==selected.documentType?` · ${selected.step}`:''}</h2>{selected.text&&<p className="source-text">{selected.text}</p>}<div className="doc-links">{selected.pdfUrl&&<a href={selected.pdfUrl} target="_blank" rel="noopener noreferrer" className="button primary"><FileDown size={17}/>Amtliches PDF öffnen</a>}<a href={selected.url} target="_blank" rel="noopener noreferrer" className="button secondary"><ArrowUpRight size={17}/>{selected.sourceId.startsWith('dip')?'Vorgang im DIP':'Originalquelle'}</a></div><hr/><dl>{[['Drucksachennummer',selected.documentNumber??'Nicht in der Quelle angegeben'],['Verfahrensschritt',selected.step??'Nicht in der Quelle angegeben'],['Vorgangstyp',selected.procedure??'Nicht in der Quelle angegeben'],['Urheber',selected.originator??'Nicht in der Quelle angegeben'],['Veröffentlicht',date(selected.publishedAt)],['Letzte Bewegung laut Quelle',selected.updatedAt?date(selected.updatedAt,true):'Nicht in der Quelle angegeben']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><span className="muted">Angezeigt werden ausschließlich die Metadaten der amtlichen Quelle. Der Inhalt wird nicht ausgewertet und nicht bewertet.</span></section>
 {!!topicsOf(selected).length&&<section className="panel fundstellen"><div className="eyebrow">FUNDSTELLEN</div><h2>Warum dieses Dokument erscheint</h2><p className="muted">Die Suche hat diese Begriffe im Titel oder Volltext gefunden. Ob der Fund für TRUMPF etwas bedeutet, entscheidet die Lektüre.</p>
 {topicsOf(selected).map(m=><div className="fund" key={m.topic}><div className="fund-kopf"><strong>{topicById(m.topic)?.label}</strong><span>{m.count} {m.count===1?'Fundstelle':'Fundstellen'}{m.inTitle?' · im Titel':''}</span></div><p className="fund-why">{topicById(m.topic)?.why}</p><blockquote className="beleg"><Quote size={13}/><span>{m.snippet}</span></blockquote><span className="muted">Gefunden über: {m.terms.join(', ')}</span></div>)}</section>}
 <aside className="panel"><h2>Gremien</h2>{lead&&<div className="body-block"><span className="badge lead">Federführend</span><strong>{lead.name}</strong><p>{lead.scope}</p></div>}
 {selected.committees.filter(c=>c!==selected.lead).map(c=>{const k=committeeById(c);return k?<div className="body-block" key={c}><span className="badge neutral">Mitberatend</span><strong>{k.name}</strong><p>{k.scope}</p></div>:null;})}
 {selected.ministries.map(m=>{const k=ministryById(m);return k?<div className="body-block" key={m}><span className="badge channel">Ressort</span><strong>{k.name}</strong><p>{k.scope}</p></div>:null;})}
 {!selected.committees.length&&!selected.ministries.length&&<p className="muted">Diese Quelle liefert keine Gremienzuordnung.</p>}
 <hr/><dl>{[['Erstmals erfasst',date(selected.firstSeen,true)],['Zuletzt abgerufen',date(selected.lastSeen,true)],['Version',String(selected.version)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>
 {!STATIC&&<button className="button secondary full" disabled={busy||!online} onClick={()=>toggleArchive(selected)}><Archive size={17}/>{selected.archived?'Wiederherstellen':'Archivieren'}</button>}</aside></div>:
 <section className="panel"><h2>Änderung zur Vorversion</h2>{!versions?<p>Versionsverlauf wird geladen. Bei fehlender Verbindung bitte erneut versuchen.</p>:versions.versions.length<2?<p>{selected.version>1?'Für dieses Dokument liegt nur ein gespeicherter Stand vor. Der Verlauf wurde beim Wiederaufbau der Datenbank gekürzt; ab der nächsten Änderung ist wieder ein Vergleich möglich.':'Es liegt ein Ausgangsstand vor. Ein Vergleich ist ab der zweiten Version möglich.'}</p>:<><div className="diff">{versions.diff.map((part,i)=><span key={i} className={part.added?'added':part.removed?'removed':''}>{part.value}</span>)}</div><p className="muted">Grün: hinzugefügt · Rot: entfernt. Verglichen werden Titel, Dokumenttyp, Verfahrensschritt und Drucksachennummer.</p></>}{versions?.versions.map(v=><details key={v.version}><summary>Version {v.version} · {date(v.changedAt,true)}</summary><p>{v.title}</p><p>{v.documentType}{v.step?' · '+v.step:''}{v.documentNumber?' · Drucksache '+v.documentNumber:''}</p><p>Datum: {date(v.publishedAt)}</p><code>SHA-256: {v.hash}</code></details>)}</section>}</>:
 view==='overview'?<><div className="page-heading"><div><div className="eyebrow">THEMENTREFFER AUS AMTLICHEN QUELLEN</div><h1>Was TRUMPF betrifft.</h1><p>Dokumente, in denen die TRUMPF-Themen vorkommen. Mit Fundstelle und Quelle, ohne Bewertung.</p></div>{STATIC?<button className="button primary" onClick={reload} disabled={busy}><RefreshCw size={17} className={busy?'spin':''}/>{busy?'Wird geladen …':'Stand neu laden'}</button>:<button className="button primary" onClick={run} disabled={busy||(!HOSTED&&!conn.token)}><RefreshCw size={17} className={busy?'spin':''}/>{busy?'Prüfung läuft …':'Quellen prüfen'}</button>}</div>
 <section className="briefing-hero"><div className="hero-top"><span className="eyebrow light"><Target size={15}/> THEMENBEZUG</span><span className="hero-time"><Clock size={14}/>{lastCheck?date(lastCheck,true):'Noch kein Quellenlauf'}</span></div>
 <h2>{relevant.length?`${relevant.length} von ${data.items.filter(i=>!i.archived).length} Dokumenten nennen ein TRUMPF-Thema.`:'Noch kein Dokument mit einem der Themenbegriffe.'}</h2>
 <p>Durchsucht werden Titel und – wo die Quelle ihn führt – der Volltext. Ein Treffer ist eine Fundstelle, keine Einschätzung: die App zeigt den Begriff und seinen Zusammenhang.</p>
 <div className="hero-bottom"><span>{latest?.summary??'Noch kein Quellenlauf.'}</span><button onClick={()=>navigate(latest?'briefings':'sources')}>{latest?'Briefing lesen':'Quellen ansehen'} <ArrowUpRight size={18}/></button></div></section>
 <div className="topicbar">{TOPICS.map(t=>{const n=topicCount(t.id);return <button key={t.id} className={'topicchip'+(topic===t.id?' chosen':'')+(n?'':' leer')} aria-pressed={topic===t.id} disabled={!n} onClick={()=>setTopic(topic===t.id?'':t.id)} title={t.why}>{t.label}<span>{n}</span></button>;})}{topic&&<button className="topicchip reset" onClick={()=>setTopic('')}>Alle Themen <X size={13}/></button>}</div>
 {!showArchive&&<section className="results"><div className="section-heading"><h2><Target size={19}/> Thementreffer <span>{shown.length}</span></h2><span className="muted">{topic?topicById(topic)?.why:'Neueste zuerst · nur die letzten 10 Tage'}</span></div>
 {shown.length?<><div className="item-list">{(alleTreffer?shown:shown.slice(0,8)).map(item=><TopicCard key={item.id} item={item} onClick={()=>setSelected(item)}/>)}</div>
 {shown.length>8&&<button className="text-button" onClick={()=>setAlleTreffer(!alleTreffer)}>{alleTreffer?'Weniger zeigen':`Alle ${shown.length} Thementreffer zeigen`}</button>}</>:
 <div className="empty"><Target size={36}/><h3>Kein Dokument mit diesen Begriffen</h3><p>{data.items.length?'Im erfassten Zeitraum kam keiner der Suchbegriffe vor. Das ist eine Aussage über die Begriffe, nicht über die Lage.':'Starte den ersten Quellenlauf.'}</p></div>}</section>}
 {!!upcoming.length&&!showArchive&&<section className="upcoming"><div className="section-heading"><h2><CalendarDays size={19}/> Als Nächstes <span>{upcoming.length}</span></h2><span className="muted">Sitzungen und Anhörungen ab heute</span></div><div className="upcoming-list">{upcoming.slice(0,6).map(i=><button key={i.id} className="upcoming-card" onClick={()=>setSelected(i)}><span className="upcoming-date">{new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'short'}).format(new Date(i.publishedAt!))}</span><strong>{i.title}</strong><span className="upcoming-body">{i.lead?committeeById(i.lead)?.name:i.institution}</span></button>)}</div></section>}
 <section className="results"><div className="section-heading"><h2>{showArchive?'Archiv':'Alle erfassten Dokumente'} <span>{matches.length}</span></h2>{!STATIC&&<button className="text-button" onClick={()=>{setShowArchive(!showArchive);setStatus('');}}><Archive size={16}/>{showArchive?'Aktive Dokumente':'Archiv'}</button>}</div><div className="search-row"><label className="search"><Search size={18}/><input aria-label="Dokumente durchsuchen" placeholder="Titel, Drucksachennummer oder Ausschuss suchen" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="Suche löschen"><X size={16}/></button>}</label><button className={'filter-button '+(filters?'selected':'')} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={18}/><span>Filter</span></button></div>
 {filters&&<div className="filters"><label>Ausschuss oder Ressort<select value={body} onChange={e=>setBody(e.target.value)}><option value="">Alle ausgewählten Gremien</option><optgroup label="Ausschüsse">{COMMITTEES.map(c=><option key={c.id} value={c.id}>{c.short}</option>)}</optgroup><optgroup label="Ressorts">{MINISTRIES.map(m=><option key={m.id} value={m.id}>{m.short}</option>)}</optgroup></select></label><label>Dokumenttyp<select value={docType} onChange={e=>setDocType(e.target.value)}><option value="">Alle Dokumenttypen</option>{types.map(t=><option key={t} value={t}>{t}</option>)}</select></label><label>Quelle<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Alle Quellen</option>{data.sources.map(s=><option key={s.id} value={s.id}>{s.institution} · {s.name}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as Change|'')}><option value="">Alle Status</option>{(['baseline','new','changed','unchanged'] as Change[]).map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label>Thema<select value={topic} onChange={e=>setTopic(e.target.value)}><option value="">Alle Themen</option>{TOPICS.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label><label>Veröffentlicht ab<input type="date" value={after} onChange={e=>setAfter(e.target.value)}/></label><button className="text-button" onClick={()=>{setSource('');setBody('');setStatus('');setDocType('');setAfter('');setQuery('');setTopic('');}}>Zurücksetzen</button></div>}
 {body&&<button className="active-filter" onClick={()=>setBody('')}>{committeeById(body)?.short??ministryById(body)?.short} <X size={14}/></button>}
 <div className="item-list">{matches.map(item=><ItemCard key={item.id} item={item} onClick={()=>setSelected(item)}/>)}{!matches.length&&<div className="empty"><Radar size={40}/><h3>{data.items.length?'Keine passenden Dokumente':'Noch kein Quellenstand'}</h3><p>{data.items.length?'Passe die Suche oder Filter an.':'Starte den ersten Quellenlauf, um die amtlichen Veröffentlichungen zu laden.'}</p>{!STATIC&&!HOSTED&&!conn.token&&<button className="button secondary" onClick={()=>navigate('settings')}>Verbindung einrichten</button>}</div>}</div></section><div className="footnote"><ShieldCheck size={16}/><span>Keine Meldung ist kein Entwarnungsnachweis. Die Anzeige gilt ausschließlich für die ausgewählten Gremien und die erfolgreich erfassten Quellen.</span></div></>:
 view==='lobby'?<><div className="page-heading"><div><div className="eyebrow">AMTLICHES LOBBYREGISTER</div><h1>Wer sich einsetzt.</h1><p>Registrierte Interessenvertretung zu deinen Themen. Selbstauskunft aus dem Register, ohne Bewertung.</p></div></div>
 <div className="notice"><ShieldCheck size={20}/><span><strong>Wozu diese Seite?</strong> Sie zeigt, an welchen Gesetzesvorhaben sich andere gerade abarbeiten — Verbände, Wettbewerber, Forschungseinrichtungen. Wo viele gleichzeitig arbeiten, bewegt sich etwas. Jedes Vorhaben verlinkt die zugehörige Drucksache. Quelle ist die Selbstauskunft im amtlichen Register: es zeigt, wer sich <strong>registriert</strong> hat, nicht wer tatsächlich Einfluss nimmt.</span></div>
 <div className="topicbar">{TOPICS.map(t=>{const n=(data.lobby??[]).filter(e=>e.topics.includes(t.id)).length;return <button key={t.id} className={'topicchip'+(topic===t.id?' chosen':'')+(n?'':' leer')} aria-pressed={topic===t.id} disabled={!n} onClick={()=>setTopic(topic===t.id?'':t.id)} title={t.why}>{t.label}<span>{n}</span></button>;})}{topic&&<button className="topicchip reset" onClick={()=>setTopic('')}>Alle Themen <X size={13}/></button>}</div>
 <section className="results"><div className="section-heading"><h2><Users size={19}/> Akteure <span>{lobby.length}</span></h2><span className="muted">Sortiert nach Themenbreite und Zahl der Vorhaben</span></div>
 {lobby.length?<div className="item-list">{lobby.map(e=><a key={e.registerNumber} className={'lobby-card'+(e.own?' eigen':'')} href={e.url} target="_blank" rel="noopener noreferrer">
  <div className="lobby-kopf"><div><strong>{e.name}</strong><span className="lobby-typ">{e.kind}{e.own&&' · eigener Eintrag'}</span></div><ArrowUpRight size={17}/></div>
  <div className="tags">{e.topics.map(id=><span key={id} className="badge topic">{topicById(id)?.label}</span>)}</div>
  <div className="lobby-zahlen">
   <span><FileText size={14}/>{e.projects} {e.projects===1?'Vorhaben gemeldet':'Vorhaben gemeldet'}</span>
   {e.statements>0&&<span><Quote size={14}/>{e.statements} Stellungnahme{e.statements===1?'':'n'}</span>}
   {e.staffFte!==null&&<span><Users size={14}/>{e.staffFte.toLocaleString('de-DE')} Vollzeitstellen</span>}
   {geld(e)&&<span><Euro size={14}/>{geld(e)}{e.fiscalYear?` (${e.fiscalYear})`:''}</span>}
   {e.updatedAt&&<span><Clock size={14}/>Stand {date(e.updatedAt)}</span>}
  </div>
  {(() => {const vs=(e.projectList??[]).filter((v:LobbyProject)=>v.topics.length&&(!topic||v.topics.includes(topic)));
   if(!vs.length)return e.projects>0?<p className="lobby-felder">{e.projects} Vorhaben gemeldet, keines davon zu deinen Themen.</p>:null;
   return <div className="vorhaben"><span className="vorhaben-kopf">Arbeitet an diesen Vorhaben zu deinen Themen</span>
    {vs.slice(0,4).map((v:LobbyProject)=><div className="vorhaben-zeile" key={v.number}><strong>{v.title}</strong>
     <span>{v.topics.map(id=>topicById(id)?.label).filter(Boolean).join(' · ')}{v.printingNumber?` · Drucksache ${v.printingNumber}`:''}</span></div>)}
    {vs.length>4&&<span className="vorhaben-mehr">und {vs.length-4} weitere</span>}</div>;})()}
  {!!e.fields.length&&<p className="lobby-felder">{e.fields.join(' · ')}</p>}
 </a>)}</div>:
 <div className="empty"><Users size={36}/><h3>Keine Einträge</h3><p>{data.lobby?.length?'Zu diesem Thema ist niemand mit mindestens zwei deiner Themen registriert.':'Noch kein Quellenlauf, oder das Register war nicht erreichbar.'}</p></div>}</section></>:
 view==='committees'?<><div className="page-heading"><div><div className="eyebrow">DIE AUSWAHL</div><h1>Ausschüsse & Ressorts.</h1><p>Nur diese Gremien werden überwacht. Alles andere wird verworfen, bevor es in die App kommt.</p></div></div>
 <div className="notice"><ShieldCheck size={20}/><span>Die Auswahl ist die einzige inhaltliche Entscheidung des Systems. Einzelne Dokumente werden danach nicht mehr gewichtet.</span></div>
 {(['Bundestag','Bundesrat'] as const).map(inst=><section className="body-section" key={inst}><h2>{inst}</h2><div className="body-grid">{COMMITTEES.filter(c=>c.institution===inst).map(c=>{const items=activeIn(c.id);return <button className="body-card" key={c.id} onClick={()=>openBody(c.id)}><div className="body-top"><Landmark size={19}/><strong>{items.length}</strong></div><h3>{c.name}</h3><p>{c.scope}</p><span className="body-foot">{items.filter(i=>i.change==='new'||i.change==='changed').length} neu oder geändert <ChevronRight size={15}/></span></button>;})}</div></section>)}
 <section className="body-section"><h2>Ressorts</h2><div className="body-grid">{MINISTRIES.map(m=>{const items=activeIn(m.id);return <button className="body-card" key={m.id} onClick={()=>openBody(m.id)}><div className="body-top"><Building2 size={19}/><strong>{items.length}</strong></div><h3>{m.name}</h3><p>{m.scope}</p><span className="body-foot">{items.filter(i=>i.change==='new'||i.change==='changed').length} neu oder geändert <ChevronRight size={15}/></span></button>;})}</div></section></>:
 view==='briefings'?<><div className="page-heading"><div><div className="eyebrow">DOKUMENTIERT & NACHVOLLZIEHBAR</div><h1>Briefings.</h1><p>Gespeicherte Stände mit unveränderlichen Quellenverweisen.</p></div>{briefing&&<button className="button secondary" onClick={()=>exportBriefing(briefing)}><Download size={17}/>Exportieren</button>}</div>{data.briefings.length?<><label className="briefing-select">Briefing auswählen<select value={briefing?.id} onChange={e=>setPickedBriefing(e.target.value)}>{data.briefings.map(b=><option key={b.id} value={b.id}>{date(b.createdAt,true)}{b.baseline?' · Ausgangsstand':''}</option>)}</select></label><section className="panel briefing-summary"><div className="eyebrow">ÜBERBLICK</div><h2>{date(briefing.createdAt)}</h2><p>{briefing.summary}</p><div className="coverage"><span><Check size={15}/>{briefing.coverage.ok} geprüft</span><span><AlertCircle size={15}/>{briefing.coverage.failed} Fehler</span><span><Radio size={15}/>{briefing.coverage.manual} offen</span></div>{briefing.errors.map(e=><p className="warning-text" key={e}>{e}</p>)}</section>
 {[...new Set(briefing.items.flatMap(i=>[...i.committees,...i.ministries]))].map(g=><section className="briefing-group" key={g}><h2>{committeeById(g)?.name??ministryById(g)?.name??g}</h2>{briefing.items.filter(i=>i.committees.includes(g)||i.ministries.includes(g)).map(i=><ItemCard key={i.id} item={i} onClick={()=>setSelected(i)}/>)}</section>)}
 {!briefing.items.length&&<section className="briefing-group"><p className="muted">In diesem Lauf gab es keine neuen oder geänderten Dokumente in den ausgewählten Gremien.</p></section>}
 <section className="panel"><h2><History size={20}/> Änderungslog</h2>{data.events.slice(0,60).map(e=><button className="event" key={e.id} onClick={()=>setSelected(data.items.find(i=>i.id===e.itemId)??null)}><span className="event-mark"/><div><strong>{e.title}</strong><span>{labels[e.change]} · Version {e.version} · {date(e.at,true)}</span></div><ChevronRight size={16}/></button>)}</section></>:<div className="empty panel"><FileText size={40}/><h3>Noch kein Briefing vorhanden</h3><p>Nach einem Quellenlauf erscheint hier der gespeicherte Stand.</p></div>}</>:
 view==='sources'?<><div className="page-heading"><div><div className="eyebrow">TRANSPARENTE ABDECKUNG</div><h1>Die Quellen.</h1><p>Amtliche Veröffentlichungen. Jeder Abruf mit eigenem Status.</p></div>{STATIC?<button className="button primary" onClick={reload} disabled={busy}><RefreshCw size={17} className={busy?'spin':''}/>Stand neu laden</button>:<button className="button primary" onClick={run} disabled={busy||(!HOSTED&&!conn.token)}><RefreshCw size={17} className={busy?'spin':''}/>Quellen prüfen</button>}</div><div className="notice"><ShieldCheck size={20}/><span>„Offen“ bedeutet: Diese Quelle wird noch nicht automatisch überwacht.</span></div><div className="source-grid">{data.sources.map(s=><section className="panel source-card" key={s.id}><div className="source-top"><div className="source-symbol"><Radio size={21}/></div><span className={'badge '+(s.status==='ok'?'success':s.status==='error'?'failure':'neutral')}>{s.status==='ok'?'Abruf erfolgreich':s.status==='error'?'Abruf fehlgeschlagen':s.status==='pending'?'Bereit für Erstabruf':s.status==='setup'?'Schlüssel fehlt':'Offen'}</span></div><span className="eyebrow">{s.institution}</span><h2>{s.name}</h2><p>{s.note}</p>{s.error&&<p className="warning-text">{s.error}</p>}<div className="source-meta"><span>{s.checkedAt?date(s.checkedAt,true):'Noch kein erfolgreicher Abruf'}</span>{s.count!==undefined&&<span>{s.count} Einträge im Fenster</span>}</div><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-link">Amtliche Quelle <ArrowUpRight size={16}/></a></section>)}</div></>:
 <><div className="page-heading"><div><div className="eyebrow">DEIN WORKSPACE</div><h1>Einstellungen.</h1><p>Verbindung, Auswahlgrundlage und Betriebsstatus.</p></div></div><div className="settings-grid">{STATIC?<section className="panel"><h2>Laufend aktualisierte Seite</h2><p>Diese Seite braucht keinen Server und keinen Schlüssel. Ein Zeitplan holt alle 30 Minuten zwischen 06:00 und 22:00 Uhr Berliner Zeit die amtlichen Quellen ab und veröffentlicht den neuen Stand hier. Du öffnest die Seite und liest.</p><div className="action-box"><strong>Als App auf dem Handy</strong><p>Im Browser über „Teilen“ beziehungsweise das Menü „Zum Home-Bildschirm“ wählen. Danach startet die Seite wie eine App, auch ohne Mac.</p></div>
 <div className="action-box"><strong>Sofort neu prüfen</strong><p>„Stand neu laden“ holt den zuletzt veröffentlichten Stand. Einen neuen Abruf der amtlichen Quellen kann diese Seite nicht auslösen — sie hat keinen Server. Der Zeitplan erledigt das alle 30 Minuten; zwischendurch startest du ihn hier von Hand.</p>{REPO&&<a className="button secondary" href={`https://github.com/${REPO}/actions/workflows/monitor.yml`} target="_blank" rel="noopener noreferrer"><ArrowUpRight size={17}/>Quellenlauf auf GitHub starten</a>}</div>
 <p className="muted">Nur lesend: Archivieren und der Versionsvergleich brauchen den Server und sind hier ausgeblendet.</p></section>:<section className="panel"><h2>{HOSTED?'Online verbunden':'Monitoring-Server'}</h2><p>Der Server sammelt die Quellen und speichert ihre Versionen. Bereits geladene Stände bleiben auf diesem Gerät verfügbar.</p>{!HOSTED&&<form onSubmit={e=>{e.preventDefault();saveConnection();}}><label>Server-Adresse<input type="url" placeholder="https://monitor.example.org" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label><label>Verbindungsschlüssel<input type="password" autoComplete="off" placeholder="Persönlicher Zugangsschlüssel" value={draft.token} onChange={e=>setDraft({...draft,token:e.target.value})}/></label><button className="button primary" disabled={busy||!ready} type="submit">{busy?'Verbindung wird geprüft …':'Prüfen & speichern'}</button></form>}{HOSTED?<div className="action-box"><strong>Ohne MacBook nutzbar</strong><p>Quellen und Stände werden auf deinem privaten Online-Server gespeichert. Du benötigst nur eine Internetverbindung und deine ChatGPT-Anmeldung.</p><button className="button secondary" onClick={()=>refresh()}>Verbindung prüfen</button></div>:<p className="muted">Lokaler Betrieb: iPhone und Mac müssen denselben Server erreichen können.</p>}</section>}
 <section className="panel"><h2>Betriebsstatus</h2><dl><div><dt>Letzter Datenstand</dt><dd>{data.serverTime?date(data.serverTime,true):'Noch nicht geladen'}</dd></div><div><dt>Zeitplan</dt><dd>{STATIC?'Alle 30 Minuten zwischen 06:00 und 22:00 Berliner Zeit':data.scheduleEnabled?'Serverseitiger Zeitplan als eingerichtet gemeldet':'Zeitplan vorbereitet, noch nicht aktiviert'}</dd></div><div><dt>Überwachte Gremien</dt><dd>{COMMITTEES.length} Ausschüsse, {MINISTRIES.length} Ressorts</dd></div><div><dt>Arbeitsweise</dt><dd>Anzeigen mit Quellenverweis. Keine Relevanzbewertung, keine Priorisierung, keine KI-Zusammenfassung.</dd></div></dl><div className="action-box"><strong>Auswahl statt Bewertung</strong><p>Gefiltert wird ausschließlich über die Zuständigkeit des Gremiums. Was dort eingeht, wird unverändert mit Drucksachennummer und amtlichem PDF angezeigt.</p><button className="button secondary" onClick={()=>navigate('committees')}>Auswahl ansehen</button></div></section></div></>}
 </div><footer className="footer">POLICY MONITOR <span>Public Policy · Persönlicher Prototyp</span></footer></main><nav className="bottom-nav" aria-label="Mobile Navigation">{nav.map(([id,label,Icon])=><button className={view===id?'active':''} key={id} onClick={()=>navigate(id)}><Icon size={21}/><span>{label}</span></button>)}</nav></div></>;
}
// Zeigt den Fund, nicht ein Urteil: welches Thema, welcher Begriff, wie oft, und der Satz drumherum.
function TopicCard({item,onClick}:{item:Item;onClick:()=>void}){
 const m=topicsOf(item);
 const beleg=m[0];
 return <button className="topic-card" onClick={onClick}>
  <div className="topic-tags">{m.map(x=><span key={x.topic} className={'badge topic'+(x.inTitle?' im-titel':'')}>{topicById(x.topic)?.label}<b>{x.count}</b>{x.inTitle&&<i>im Titel</i>}</span>)}</div>
  <h3>{item.title}</h3>
  {beleg&&<blockquote className="beleg"><Quote size={13}/><span>{beleg.snippet}</span></blockquote>}
  <div className="item-meta"><span>{item.documentType}</span>{item.documentNumber&&<><span>·</span><span>Drs. {item.documentNumber}</span></>}<span>·</span><span>{date(recency(item))}</span>{item.publishedAt&&recency(item).slice(0,10)!==item.publishedAt.slice(0,10)&&<><span>·</span><span className="moved">Dokument vom {date(item.publishedAt)}</span></>}{item.lead&&<><span>·</span><span>{committeeById(item.lead)?.short}</span></>}{item.pdfUrl&&<span className="badge neutral">PDF</span>}</div>
 </button>;
}
function ItemCard({item,onClick}:{item:Item;onClick:()=>void}){
 const lead=item.lead?committeeById(item.lead):undefined;
 return <button className="item-card" onClick={onClick}><div className={'item-stripe '+item.change}/><div className="item-content"><div className="item-meta"><span>{item.documentType}</span>{item.documentNumber&&<><span>·</span><span>Drs. {item.documentNumber}</span></>}<span>·</span><span>{date(item.publishedAt)}</span>{item.updatedAt&&item.publishedAt&&item.updatedAt.slice(0,10)!==item.publishedAt.slice(0,10)&&<><span>·</span><span className="moved">bewegt {date(item.updatedAt)}</span></>}<span className="change-label">{labels[item.change]}</span></div><h3>{item.title}</h3><div className="tags">{lead&&<span className="badge lead">{lead.short} · federführend</span>}{item.committees.filter(c=>c!==item.lead).map(c=><span className="badge channel" key={c}>{committeeById(c)?.short}</span>)}{item.ministries.map(m=><span className="badge channel" key={m}>{ministryById(m)?.short}</span>)}{topicsOf(item).map(x=><span key={x.topic} className="badge topic">{topicById(x.topic)?.label}</span>)}{item.step&&item.step!==item.documentType&&<span className="badge neutral">{item.step}</span>}{item.pdfUrl&&<span className="badge neutral">PDF</span>}</div></div><ChevronRight className="item-arrow" size={19}/></button>;
}
