import Head from 'next/head';
import {useEffect,useRef,useState} from 'react';
import {Capacitor,CapacitorHttp,registerPlugin} from '@capacitor/core';
import {Radar,LayoutDashboard,FileText,Radio,Settings,Search,ArrowUpRight,RefreshCw,ChevronRight,Clock,ShieldCheck,AlertCircle,ArrowLeft,Download,Archive,History,Check,WifiOff,SlidersHorizontal,X,Bookmark} from 'lucide-react';
import {CHANNELS,SOURCES,type Dashboard,type Item,type Briefing,type Category} from '../src/model';
const OfflineCache=registerPlugin<{save(options:{payload:string}):Promise<void>}>('OfflineCache');
const HOSTED=process.env.NEXT_PUBLIC_HOSTED==='1';
const labels:Record<string,string>={baseline:'Ausgangsstand',new:'Neu',changed:'Geändert',unchanged:'Unverändert',relevant:'Relevante Änderungen',watch:'Beobachten',irrelevant:'Nicht relevant'};
const empty:Dashboard={items:[],sources:SOURCES,briefings:[],events:[],serverTime:'',aiEnabled:false,scheduleEnabled:false};
const date=(s:string|null|undefined,full=false)=>s?new Intl.DateTimeFormat('de-DE',full?{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s)):'Nicht im Text enthalten';
const nav=[['overview','Lagebild',LayoutDashboard],['briefings','Briefings',FileText],['sources','Quellen',Radio],['settings','Einstellungen',Settings]] as const;
type Connection={url:string;token:string};
async function request<T>(conn:Connection,path:string,method='GET',body?:unknown):Promise<T>{
 if(!HOSTED&&!conn.token)throw new Error('Bitte unter Einstellungen den Verbindungsschlüssel hinterlegen.');
 const url=(HOSTED?'':conn.url.replace(/\/$/,''))+'/api/'+path;
 const headers:Record<string,string>={'Content-Type':'application/json'};if(!HOSTED)headers.Authorization='Bearer '+conn.token;
 if(Capacitor.isNativePlatform()&&!HOSTED){
 const r=await CapacitorHttp.request({url,method,headers,data:body,connectTimeout:12000,readTimeout:300000,responseType:'json'});
 if(r.status<200||r.status>=300)throw new Error(r.data?.error??`Verbindung fehlgeschlagen (${r.status})`);return r.data;
 }
 const r=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(300000)});if(!r.headers.get('content-type')?.includes('application/json'))throw new Error('Bitte erneut mit ChatGPT anmelden. Dein gespeicherter Stand bleibt erhalten.');const data=await r.json() as T & {error?:string};if(!r.ok)throw new Error(data.error??'Verbindung fehlgeschlagen');return data;
}
export default function Home(){
 const [data,setData]=useState<Dashboard>(empty),[view,setView]=useState('overview'),[selected,setSelected]=useState<Item|null>(null),[category,setCategory]=useState<Category|'all'>('all');
 const [query,setQuery]=useState(''),[source,setSource]=useState(''),[channel,setChannel]=useState(''),[after,setAfter]=useState(''),[status,setStatus]=useState(''),[showArchive,setShowArchive]=useState(false),[filters,setFilters]=useState(false);
 const [conn,setConn]=useState<Connection>({url:'',token:''}),[draft,setDraft]=useState<Connection>({url:'',token:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[online,setOnline]=useState(false),[ready,setReady]=useState(false);
 const [pickedBriefing,setPickedBriefing]=useState<string>(''),[versions,setVersions]=useState<{versions:Item[];diff:{added?:boolean;removed?:boolean;value:string}[]}|null>(null),[tab,setTab]=useState('detail');
 const mainRef=useRef<HTMLElement>(null);
 const cache=(d:Dashboard)=>{setData(d);try{localStorage.setItem('policy-cache',JSON.stringify(d));if(Capacitor.isNativePlatform())void OfflineCache.save({payload:JSON.stringify(d)}).catch(()=>{});}catch{}};
 async function refresh(c=conn){setError('');try{const d=await request<Dashboard>(c,'dashboard');cache(d);setOnline(true);return true;}catch(e){setOnline(false);setError(e instanceof Error&&/timed? ?out|timeout|network|fetch/i.test(e.message)?'Die Verbindung dauert zu lange. Bitte Internetverbindung prüfen und erneut versuchen. Dein gespeicherter Stand bleibt erhalten.':e instanceof Error?e.message:'Keine Verbindung. Dein gespeicherter Stand bleibt erhalten.');return false;}}
 useEffect(()=>{let active=true;(async()=>{let saved:Connection={url:'',token:''};try{saved=JSON.parse(localStorage.getItem('policy-connection')??'null')??saved;const cached=JSON.parse(localStorage.getItem('policy-cache')??'null');if(cached)setData(cached);}catch{}
 if(!HOSTED&&!saved.token){try{const r=await fetch('/connection.json');if(r.ok)saved=await r.json();}catch{}}
 try{if(!HOSTED&&!localStorage.getItem('policy-cache')){const r=await fetch('/bootstrap.json');if(r.ok&&active)setData(await r.json());}}catch{}
 if(!active)return;setConn(saved);setDraft(saved);setReady(true);if(saved.token||HOSTED)await refresh(saved);
 })();return()=>{active=false;};},[]);
 useEffect(()=>{if(selected){setTab('detail');setVersions(null);mainRef.current?.scrollTo(0,0);} },[selected?.id]);
 useEffect(()=>{if(!ready)return;const onVisible=()=>{if(document.visibilityState==='visible'&&(HOSTED||conn.token))void refresh();};document.addEventListener('visibilitychange',onVisible);return()=>document.removeEventListener('visibilitychange',onVisible);},[ready,conn.url,conn.token]);
 const latest=data.briefings[0];
 const briefing=data.briefings.find(b=>b.id===pickedBriefing)??latest;
 const matches=data.items.filter(i=>i.archived===showArchive&&(category==='all'||i.evaluation.category===category)&&(!source||i.sourceId===source)&&(!channel||i.evaluation.channels.includes(channel))&&(!status||i.change===status)&&(!after||!!i.publishedAt&&i.publishedAt.slice(0,10)>=after)&&(!query||(i.title+' '+i.text+' '+i.institution).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>b.evaluation.score-a.evaluation.score||b.changedAt.localeCompare(a.changedAt));
 const counts=(c:Category)=>data.items.filter(i=>!i.archived&&i.evaluation.category===c).length;
 async function run(){setBusy(true);setError('');setNotice('Quellen werden geprüft …');try{const r=await request<{briefing:Briefing}>(conn,'run','POST');await refresh();setNotice(r.briefing.summary);}catch(e){setNotice('');setError(e instanceof Error?e.message:'Quellenlauf fehlgeschlagen.');}finally{setBusy(false);}}
 function navigate(to:string){setSelected(null);setView(to);setNotice('');mainRef.current?.scrollTo(0,0);}
 async function saveConnection(){try{const u=new URL(draft.url||window.location.origin);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw new Error('Bitte eine gültige Server-Adresse eingeben.');const next={url:u.origin,token:draft.token.trim()};if(!next.token)throw new Error('Verbindungsschlüssel fehlt.');setBusy(true);if(await refresh(next)){localStorage.setItem('policy-connection',JSON.stringify(next));setConn(next);setNotice('Verbindung gespeichert.');}}catch(e){setError(e instanceof Error?e.message:'Verbindung ungültig.');}finally{setBusy(false);}}
 async function exportBriefing(b:Briefing){const text=['POLICY MONITOR · TRUMPF',date(b.createdAt,true),b.summary,...(['relevant','watch','irrelevant'] as Category[]).flatMap(c=>['\n'+labels[c],...b.items.filter(i=>i.evaluation.category===c).map(i=>`${i.title}\n${labels[i.change]} · ${i.institution}\n${i.evaluation.reason}\nBeleg: ${i.evaluation.evidence.join(' / ')||'Nicht im Text enthalten'}\nQuelle: ${i.url}\nPrüfungsvorschlag: ${i.evaluation.action}`)])].join('\n\n');try{if(navigator.share){await navigator.share({title:'Policy Briefing '+b.day,text});}else{const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`Briefing-${b.day}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(e){if((e as Error).name!=='AbortError')setError('Export fehlgeschlagen.');}}
 async function toggleArchive(item:Item){setBusy(true);try{await request(conn,'items/'+item.id,'PATCH',{archived:!item.archived});await refresh();setSelected({...item,archived:!item.archived});setNotice(item.archived?'Treffer wiederhergestellt.':'Treffer archiviert.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function loadHistory(){setTab('history');try{setVersions(await request(conn,'history/'+selected!.id));}catch(e){setError((e as Error).message);}}
 return <><Head><title>Policy Monitor · TRUMPF</title><meta name="description" content="Regulatorisches Frühwarn-Monitoring für Public Policy"/><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/><meta name="theme-color" content="#1038d4"/></Head>
 <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brandmark"><Radar size={27}/></div><div><strong>TRUMPF</strong><span>PUBLIC POLICY</span></div></div><div className="workspace">MONITORING WORKSPACE</div><nav aria-label="Hauptnavigation">{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>navigate(id)}><Icon size={20}/><span>{label}</span>{view===id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><ShieldCheck size={21}/><div><strong>Amtliche Quellen</strong><span>Belege vor Bewertung</span></div></div></aside>
 <main ref={mainRef} className="main"><header className="topbar"><div className="mobile-brand"><Radar size={22}/><b>TRUMPF</b><span>Policy Monitor</span></div><div className="breadcrumb">Public Policy <ChevronRight size={14}/> {nav.find(n=>n[0]===view)?.[1]}</div><div className={'connection '+(online?'connected':'')}><span/>{online?'Verbunden':data.items.length?'Gespeicherter Stand':'Noch nicht verbunden'}</div></header>
 <div className="content">{error&&<div className="notice error" role="alert"><AlertCircle size={19}/><span>{error}{HOSTED&&error.includes('anmelden')&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top"> Jetzt anmelden</a>}</span><button aria-label="Meldung schließen" onClick={()=>setError('')}><X size={17}/></button></div>}{notice&&<div className="notice" role="status"><Check size={19}/><span>{notice}</span></div>}
 {selected?<><button className="back" onClick={()=>setSelected(null)}><ArrowLeft size={18}/> Zurück zur Übersicht</button><div className="detail-heading"><div className="eyebrow">{selected.institution} · {selected.documentType}</div><h1>{selected.title}</h1><div className="tags"><span className={'badge '+selected.evaluation.category}>{labels[selected.evaluation.category]}</span><span className="badge neutral">{labels[selected.change]}</span>{selected.archived&&<span className="badge neutral">Archiviert</span>}</div></div><div className="detail-tabs"><button className={tab==='detail'?'active':''} onClick={()=>setTab('detail')}>Einordnung & Belege</button><button className={tab==='history'?'active':''} onClick={loadHistory}>Versionen & Änderungen</button></div>
 {tab==='detail'?<div className="detail-grid"><section className="panel"><div className="eyebrow">QUELLENTEXT · {selected.text?'FEED-AUSZUG':'NUR TITEL'}</div><p className="source-text">{selected.text||selected.title}</p><a href={selected.url} target="_blank" rel="noopener noreferrer" className="text-link">Originalquelle öffnen <ArrowUpRight size={17}/></a><hr/><h2>Vorläufige Einordnung</h2><p>{selected.evaluation.reason}</p><div className="evidence"><strong>Textbelege</strong>{selected.evaluation.evidence.length?selected.evaluation.evidence.map((q,i)=><blockquote key={i}>„{q}“</blockquote>):<p>Nicht im Text enthalten</p>}</div><div className="action-box"><span className="eyebrow">PRÜFUNGSVORSCHLAG</span><p>{selected.evaluation.action}</p></div><span className="muted">{selected.evaluation.method}. Keine freigegebene fachliche Bewertung.</span></section><aside className="panel"><h2>Screening</h2><dl>{[['Priorität',`${selected.evaluation.triage} · Score ${selected.evaluation.score}/100`],['Materialität',selected.evaluation.materiality],['Einflussfenster',selected.evaluation.window],['Hebel / Akteure',selected.evaluation.actors],['Zuständigkeit',selected.evaluation.owner],['Stufe A–E',selected.evaluation.stage],['Verfahrensstand',selected.procedure??'Nicht im Text enthalten'],['Veröffentlicht',date(selected.publishedAt)],['Zuletzt abgerufen',date(selected.lastSeen,true)],['Version',String(selected.version)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="tags">{selected.evaluation.channels.map(c=><span className="badge channel" key={c}>{c} · {CHANNELS[c]}</span>)}</div><button className="button secondary full" disabled={busy||!online} onClick={()=>toggleArchive(selected)}><Archive size={17}/>{selected.archived?'Wiederherstellen':'Archivieren'}</button></aside></div>:<section className="panel"><h2>Änderung zur Vorversion</h2>{!versions?<p>Versionsverlauf wird geladen. Bei fehlender Verbindung bitte erneut versuchen.</p>:versions.versions.length<2?<p>Es liegt ein Ausgangsstand vor. Ein Vergleich ist ab der zweiten Version möglich.</p>:<><div className="diff">{versions.diff.map((part,i)=><span key={i} className={part.added?'added':part.removed?'removed':''}>{part.value}</span>)}</div><p className="muted">Grün: hinzugefügt · Rot: entfernt. Verglichen werden Titel, Feed-Text und Verfahrensstand.</p></>}{versions?.versions.map(v=><details key={v.version}><summary>Version {v.version} · {date(v.changedAt,true)}</summary><p>{v.title}</p><p>{v.text||'Kein Feed-Text enthalten.'}</p><p>Datum: {date(v.publishedAt)} · Verfahren: {v.procedure??'Nicht im Text enthalten'}</p><code>SHA-256: {v.hash}</code></details>)}</section>}</>:
 view==='overview'?<><div className="page-heading"><div><div className="eyebrow">REGULATORISCHES FRÜHWARN-MONITORING</div><h1>Das Lagebild.</h1><p>Was sich verändert hat. Was Aufmerksamkeit braucht.</p></div><button className="button primary" onClick={run} disabled={busy||(!HOSTED&&!conn.token)}><RefreshCw size={17} className={busy?'spin':''}/>{busy?'Prüfung läuft …':'Quellen prüfen'}</button></div>
 <section className="briefing-hero"><div className="hero-top"><span className="eyebrow light"><FileText size={15}/> LETZTES BRIEFING</span><span className="hero-time"><Clock size={14}/>{latest?date(latest.createdAt,true):'Noch kein Quellenlauf'}</span></div><h2>{latest?(latest.baseline?'Der Ausgangsstand ist erfasst.':'Die Änderungen im Überblick.'):'Dein Monitoring ist bereit.'}</h2><p>{latest?.summary??'Prüfe die angebundenen amtlichen Quellen. Jeder Befund erhält einen Quellennachweis; ab dem zweiten Stand werden Änderungen sichtbar.'}</p><div className="hero-bottom"><span>{data.sources.filter(s=>s.status==='ok').length} von {data.sources.length} Quellen zuletzt erfolgreich geprüft</span><button onClick={()=>navigate(latest?'briefings':'sources')}>{latest?'Briefing lesen':'Quellen ansehen'} <ArrowUpRight size={18}/></button></div></section>
 <div className="metrics">{(['relevant','watch','irrelevant'] as Category[]).map((c,i)=><button key={c} aria-pressed={category===c} className={'metric '+c+(category===c?' chosen':'')} onClick={()=>setCategory(category===c?'all':c)}><div><span className="metric-dot"/>{labels[c]}</div><strong>{counts(c).toString().padStart(2,'0')}</strong><span>{i===0?'Fachliche Prüfung erforderlich':i===1?'Thematische Kandidaten':'Vorläufige Triage'}</span></button>)}</div>
 <section className="results"><div className="section-heading"><h2>{showArchive?'Archiv':'Erfasste Vorgänge'} <span>{matches.length}</span></h2><button className="text-button" onClick={()=>{setShowArchive(!showArchive);setCategory('all');}}><Archive size={16}/>{showArchive?'Aktive Treffer':'Archiv'}</button></div><div className="search-row"><label className="search"><Search size={18}/><input aria-label="Vorgänge durchsuchen" placeholder="Titel, Thema oder Institution suchen" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="Suche löschen"><X size={16}/></button>}</label><button className={'filter-button '+(filters?'selected':'')} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={18}/><span>Filter</span></button></div>
 {filters&&<div className="filters"><label>Quelle<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Alle Quellen</option>{data.sources.map(s=><option key={s.id} value={s.id}>{s.institution} · {s.name}</option>)}</select></label><label>TRUMPF-Kanal<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="">Alle Kanäle</option>{Object.entries(CHANNELS).map(([k,v])=><option key={k} value={k}>{k} · {v}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Alle Status</option>{['baseline','new','changed','unchanged'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label>Veröffentlicht ab<input type="date" value={after} onChange={e=>setAfter(e.target.value)}/></label><button className="text-button" onClick={()=>{setSource('');setChannel('');setStatus('');setAfter('');setCategory('all');setQuery('');}}>Zurücksetzen</button></div>}
 {category!=='all'&&<button className="active-filter" onClick={()=>setCategory('all')}>{labels[category]} <X size={14}/></button>}
 <div className="item-list">{matches.map(item=><ItemCard key={item.id} item={item} onClick={()=>setSelected(item)}/>)}{!matches.length&&<div className="empty"><Radar size={40}/><h3>{data.items.length?'Keine passenden Treffer':'Noch kein Quellenstand'}</h3><p>{data.items.length?'Passe die Suche oder Filter an.':'Starte den ersten Quellenlauf, um die amtlichen Veröffentlichungen zu laden.'}</p>{!HOSTED&&!conn.token&&<button className="button secondary" onClick={()=>navigate('settings')}>Verbindung einrichten</button>}</div>}</div></section><div className="footnote"><ShieldCheck size={16}/><span>Keine Meldung ist kein Entwarnungsnachweis. Die Aussage gilt ausschließlich für erfolgreich erfasste Quellen.</span></div></>:
 view==='briefings'?<><div className="page-heading"><div><div className="eyebrow">DOKUMENTIERT & NACHVOLLZIEHBAR</div><h1>Briefings.</h1><p>Gespeicherte Lagebilder mit unveränderlichen Quellenständen.</p></div>{briefing&&<button className="button secondary" onClick={()=>exportBriefing(briefing)}><Download size={17}/>Exportieren</button>}</div>{data.briefings.length?<><label className="briefing-select">Lagebild auswählen<select value={briefing?.id} onChange={e=>setPickedBriefing(e.target.value)}>{data.briefings.map(b=><option key={b.id} value={b.id}>{date(b.createdAt,true)}{b.baseline?' · Ausgangsstand':''}</option>)}</select></label><section className="panel briefing-summary"><div className="eyebrow">EXECUTIVE SUMMARY</div><h2>{date(briefing.createdAt)}</h2><p>{briefing.summary}</p><div className="coverage"><span><Check size={15}/>{briefing.coverage.ok} geprüft</span><span><AlertCircle size={15}/>{briefing.coverage.failed} Fehler</span><span><Radio size={15}/>{briefing.coverage.manual} offen</span></div>{briefing.errors.map(e=><p className="warning-text" key={e}>{e}</p>)}</section>{(['relevant','watch','irrelevant'] as Category[]).map(c=><section className="briefing-group" key={c}><h2>{labels[c]}</h2>{briefing.items.filter(i=>i.evaluation.category===c).length?briefing.items.filter(i=>i.evaluation.category===c).map(i=><ItemCard key={i.id} item={i} onClick={()=>setSelected(i)}/>):<p className="muted">Keine entsprechenden neuen oder geänderten Einträge in diesem Lauf.</p>}</section>)}<section className="panel"><h2><History size={20}/> Änderungslog</h2>{data.events.slice(0,60).map(e=><button className="event" key={e.id} onClick={()=>setSelected(data.items.find(i=>i.id===e.itemId)??null)}><span className="event-mark"/><div><strong>{e.title}</strong><span>{labels[e.change]} · Version {e.version} · {date(e.at,true)}</span></div><ChevronRight size={16}/></button>)}</section></>:<div className="empty panel"><FileText size={40}/><h3>Noch kein Briefing vorhanden</h3><p>Nach einem Quellenlauf erscheint hier das gespeicherte Lagebild.</p></div>}</>:
 view==='sources'?<><div className="page-heading"><div><div className="eyebrow">TRANSPARENTE ABDECKUNG</div><h1>Die Quellen.</h1><p>Amtliche Veröffentlichungen. Jeder Abruf mit eigenem Status.</p></div><button className="button primary" onClick={run} disabled={busy||(!HOSTED&&!conn.token)}><RefreshCw size={17} className={busy?'spin':''}/>Quellen prüfen</button></div><div className="notice"><ShieldCheck size={20}/><span>„Offen“ bedeutet: Diese Quelle wird noch nicht automatisch überwacht.</span></div><div className="source-grid">{data.sources.map(s=><section className="panel source-card" key={s.id}><div className="source-top"><div className="source-symbol"><Radio size={21}/></div><span className={'badge '+(s.status==='ok'?'success':s.status==='error'?'failure':'neutral')}>{s.status==='ok'?'Abruf erfolgreich':s.status==='error'?'Abruf fehlgeschlagen':s.status==='pending'?'Bereit für Erstabruf':'Offen'}</span></div><span className="eyebrow">{s.institution}</span><h2>{s.name}</h2><p>{s.note}</p>{s.error&&<p className="warning-text">{s.error}</p>}<div className="source-meta"><span>{s.checkedAt?date(s.checkedAt,true):'Noch kein erfolgreicher Abruf'}</span>{s.count!==undefined&&<span>{s.count} Einträge</span>}</div><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-link">Amtliche Quelle <ArrowUpRight size={16}/></a></section>)}</div></>:
 <><div className="page-heading"><div><div className="eyebrow">DEIN WORKSPACE</div><h1>Einstellungen.</h1><p>Verbindung, Bewertungsgrundlage und Betriebsstatus.</p></div></div><div className="settings-grid"><section className="panel"><h2>{HOSTED?'Online verbunden':'Monitoring-Server'}</h2><p>Der Server sammelt die Quellen und speichert ihre Versionen. Bereits geladene Lagebilder bleiben auf diesem Gerät verfügbar.</p>{!HOSTED&&<form onSubmit={e=>{e.preventDefault();saveConnection();}}><label>Server-Adresse<input type="url" placeholder="https://monitor.example.org" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label><label>Verbindungsschlüssel<input type="password" autoComplete="off" placeholder="Persönlicher Zugangsschlüssel" value={draft.token} onChange={e=>setDraft({...draft,token:e.target.value})}/></label><button className="button primary" disabled={busy||!ready} type="submit">{busy?'Verbindung wird geprüft …':'Prüfen & speichern'}</button></form>}{HOSTED?<div className="action-box"><strong>Ohne MacBook nutzbar</strong><p>Quellen und Briefings werden auf deinem privaten Online-Server gespeichert. Du benötigst nur eine Internetverbindung und deine ChatGPT-Anmeldung.</p><button className="button secondary" onClick={()=>refresh()}>Verbindung prüfen</button></div>:<p className="muted">Lokaler Betrieb: iPhone und Mac müssen denselben Server erreichen können.</p>}</section><section className="panel"><h2>Betriebsstatus</h2><dl><div><dt>Letzter Datenstand</dt><dd>{data.serverTime?date(data.serverTime,true):'Noch nicht geladen'}</dd></div><div><dt>Morgenbriefing · 06:00 Berlin</dt><dd>{data.scheduleEnabled?'Serverseitiger Zeitplan als eingerichtet gemeldet':'Zeitplan vorbereitet, noch nicht aktiviert'}</dd></div><div><dt>Bewertungsmodus</dt><dd>{data.aiEnabled?'KI-Vorschläge mit Textbelegprüfung':'Regelbasierte Vorprüfung; KI nicht eingerichtet'}</dd></div><div><dt>Screening A–E</dt><dd>Die Definitionen fehlen in der Spezifikation. Es werden keine Stufen erfunden.</dd></div></dl><div className="action-box"><strong>Quellen vor Schlussfolgerungen</strong><p>Scores sind Such- und Priorisierungshilfen. Materialität, Einflussfenster und Zuständigkeit bleiben ohne Textbeleg offen.</p></div></section><section className="panel channels-panel"><h2>Die zehn TRUMPF-Kanäle</h2><div className="channel-list">{Object.entries(CHANNELS).map(([k,v])=><div key={k}><span>{k}</span>{v}</div>)}</div></section></div></>}
 </div><footer className="footer">POLICY MONITOR <span>Public Policy · Persönlicher Prototyp</span></footer></main><nav className="bottom-nav" aria-label="Mobile Navigation">{nav.map(([id,label,Icon])=><button className={view===id?'active':''} key={id} onClick={()=>navigate(id)}><Icon size={21}/><span>{label}</span></button>)}</nav></div></>;
}
function ItemCard({item,onClick}:{item:Item;onClick:()=>void}){return <button className="item-card" onClick={onClick}><div className={'item-stripe '+item.evaluation.category}/><div className="item-content"><div className="item-meta"><span>{item.institution}</span><span>·</span><span>{date(item.publishedAt)}</span><span className="change-label">{labels[item.change]}</span></div><h3>{item.title}</h3><p>{item.evaluation.reason}</p><div className="tags">{item.evaluation.channels.map(c=><span className="badge channel" key={c}>{c} · {CHANNELS[c]}</span>)}<span className={'badge '+item.evaluation.category}>{item.evaluation.triage}</span></div></div><ChevronRight className="item-arrow" size={19}/></button>;}
