import Head from 'next/head';
import {useEffect,useRef,useState} from 'react';
import {Capacitor,CapacitorHttp,registerPlugin} from '@capacitor/core';
import {Radar,LayoutDashboard,FileText,Radio,Settings,Search,ArrowUpRight,RefreshCw,ChevronRight,Clock,ShieldCheck,AlertCircle,ArrowLeft,Download,Archive,History,Check,SlidersHorizontal,X,Landmark,FileDown,Building2} from 'lucide-react';
import {COMMITTEES,MINISTRIES,SOURCES,committeeById,type Dashboard,type Item,type Briefing,type Change} from '../src/model';
const OfflineCache=registerPlugin<{save(options:{payload:string}):Promise<void>}>('OfflineCache');
const HOSTED=process.env.NEXT_PUBLIC_HOSTED==='1';
// Statischer Betrieb auf GitHub Pages: kein Server, kein Schlüssel. Die Seite liest den Stand,
// den der tägliche Lauf in bootstrap.json geschrieben hat. Alles, was einen Server braucht, entfällt.
const STATIC=process.env.NEXT_PUBLIC_STATIC==='1';
const labels:Record<string,string>={baseline:'Ausgangsstand',new:'Neu',changed:'Geändert',unchanged:'Unverändert'};
const ministryById=(id:string)=>MINISTRIES.find(m=>m.id===id);
const empty:Dashboard={items:[],sources:SOURCES,briefings:[],events:[],serverTime:'',scheduleEnabled:false};
const date=(s:string|null|undefined,full=false)=>s?new Intl.DateTimeFormat('de-DE',full?{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s)):'Kein Datum in der Quelle';
const bodies=(i:Item)=>[...i.committees.map(c=>committeeById(c)?.short),...i.ministries.map(m=>ministryById(m)?.short)].filter(Boolean) as string[];
const nav=[['overview','Lagebild',LayoutDashboard],['committees','Ausschüsse',Landmark],['briefings','Briefings',FileText],['sources','Quellen',Radio],['settings','Einstellungen',Settings]] as const;
type Connection={url:string;token:string};
async function request<T>(conn:Connection,path:string,method='GET',body?:unknown):Promise<T>{
 if(!HOSTED&&!conn.token)throw new Error('Bitte unter Einstellungen den Verbindungsschlüssel hinterlegen.');
 const url=(HOSTED?'':conn.url.replace(/\/$/,''))+'/api/'+path;
 const headers:Record<string,string>={'Content-Type':'application/json'};if(!HOSTED)headers.Authorization='Bearer '+conn.token;
 if(Capacitor.isNativePlatform()&&!HOSTED){
 const r=await CapacitorHttp.request({url,method,headers,data:body,connectTimeout:12000,readTimeout:300000,responseType:'json'});
 if(r.status<200||r.status>=300)throw new Error(r.data?.error??`Verbindung fehlgeschlagen (${r.status})`);return r.data;
 }
 const r=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(300000)});if(!r.headers.get('content-type')?.includes('application/json'))throw new Error('Bitte erneut mit ChatGPT anmelden. Dein gespeicherter Stand bleibt erhalten.');const data=await r.json() as T & {error?:string};if(!r.ok)throw new Error(data.error??'Verbindung fehlgeschlagen');return data;
}
export default function Home(){
 const [data,setData]=useState<Dashboard>(empty),[view,setView]=useState('overview'),[selected,setSelected]=useState<Item|null>(null);
 const [query,setQuery]=useState(''),[source,setSource]=useState(''),[body,setBody]=useState(''),[after,setAfter]=useState(''),[status,setStatus]=useState<Change|''>(''),[docType,setDocType]=useState(''),[showArchive,setShowArchive]=useState(false),[filters,setFilters]=useState(false);
 const [conn,setConn]=useState<Connection>({url:'',token:''}),[draft,setDraft]=useState<Connection>({url:'',token:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[online,setOnline]=useState(false),[ready,setReady]=useState(false);
 const [pickedBriefing,setPickedBriefing]=useState<string>(''),[versions,setVersions]=useState<{versions:Item[];diff:{added?:boolean;removed?:boolean;value:string}[]}|null>(null),[tab,setTab]=useState('detail');
 const mainRef=useRef<HTMLElement>(null);
 const cache=(d:Dashboard)=>{setData(d);try{localStorage.setItem('policy-cache',JSON.stringify(d));if(Capacitor.isNativePlatform())void OfflineCache.save({payload:JSON.stringify(d)}).catch(()=>{});}catch{}};
 async function refresh(c=conn){setError('');try{const d=await request<Dashboard>(c,'dashboard');cache(d);setOnline(true);return true;}catch(e){setOnline(false);setError(e instanceof Error&&/timed? ?out|timeout|network|fetch/i.test(e.message)?'Die Verbindung dauert zu lange. Bitte Internetverbindung prüfen und erneut versuchen. Dein gespeicherter Stand bleibt erhalten.':e instanceof Error?e.message:'Keine Verbindung. Dein gespeicherter Stand bleibt erhalten.');return false;}}
 useEffect(()=>{let active=true;(async()=>{
 if(STATIC){try{const r=await fetch(new URL('bootstrap.json',window.location.href).href,{cache:'no-store'});if(!r.ok)throw new Error();if(active){setData(await r.json());setOnline(true);}}catch{if(active)setError('Der gespeicherte Stand konnte nicht geladen werden. Bitte Seite neu laden.');}finally{if(active)setReady(true);}return;}
 let saved:Connection={url:'',token:''};try{saved=JSON.parse(localStorage.getItem('policy-connection')??'null')??saved;const cached=JSON.parse(localStorage.getItem('policy-cache')??'null');if(cached)setData(cached);}catch{}
 if(!HOSTED&&!saved.token){try{const r=await fetch('/connection.json');if(r.ok)saved=await r.json();}catch{}}
 try{if(!HOSTED&&!localStorage.getItem('policy-cache')){const r=await fetch('/bootstrap.json');if(r.ok&&active)setData(await r.json());}}catch{}
 if(!active)return;setConn(saved);setDraft(saved);setReady(true);if(saved.token||HOSTED)await refresh(saved);
 })();return()=>{active=false;};},[]);
 useEffect(()=>{if(selected){setTab('detail');setVersions(null);mainRef.current?.scrollTo(0,0);} },[selected?.id]);
 useEffect(()=>{if(!ready)return;const onVisible=()=>{if(document.visibilityState==='visible'&&(HOSTED||conn.token))void refresh();};document.addEventListener('visibilitychange',onVisible);return()=>document.removeEventListener('visibilitychange',onVisible);},[ready,conn.url,conn.token]);
 const latest=data.briefings[0];
 const briefing=data.briefings.find(b=>b.id===pickedBriefing)??latest;
 const types=[...new Set(data.items.map(i=>i.documentType))].sort();
 const matches=data.items.filter(i=>i.archived===showArchive&&(!source||i.sourceId===source)&&(!body||i.committees.includes(body)||i.ministries.includes(body))&&(!status||i.change===status)&&(!docType||i.documentType===docType)&&(!after||!!i.publishedAt&&i.publishedAt.slice(0,10)>=after)&&(!query||(i.title+' '+i.documentNumber+' '+i.documentType+' '+bodies(i).join(' ')).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>b.changedAt.localeCompare(a.changedAt));
 const counts=(c:Change)=>data.items.filter(i=>!i.archived&&i.change===c).length;
 const activeIn=(id:string)=>data.items.filter(i=>!i.archived&&(i.committees.includes(id)||i.ministries.includes(id)));
 async function run(){setBusy(true);setError('');setNotice('Quellen werden geprüft …');try{const r=await request<{briefing:Briefing}>(conn,'run','POST');await refresh();setNotice(r.briefing.summary);}catch(e){setNotice('');setError(e instanceof Error?e.message:'Quellenlauf fehlgeschlagen.');}finally{setBusy(false);}}
 function navigate(to:string){setSelected(null);setView(to);setNotice('');mainRef.current?.scrollTo(0,0);}
 function focusBody(id:string){setBody(id);setStatus('');setShowArchive(false);setFilters(true);navigate('overview');}
 async function saveConnection(){try{const u=new URL(draft.url||window.location.origin);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw new Error('Bitte eine gültige Server-Adresse eingeben.');const next={url:u.origin,token:draft.token.trim()};if(!next.token)throw new Error('Verbindungsschlüssel fehlt.');setBusy(true);if(await refresh(next)){localStorage.setItem('policy-connection',JSON.stringify(next));setConn(next);setNotice('Verbindung gespeichert.');}}catch(e){setError(e instanceof Error?e.message:'Verbindung ungültig.');}finally{setBusy(false);}}
 async function exportBriefing(b:Briefing){
 const entry=(i:Item)=>[i.title,`${labels[i.change]} · ${i.documentType}${i.step?' · '+i.step:''}${i.documentNumber?' · Drucksache '+i.documentNumber:''}`,`Datum: ${date(i.publishedAt)}`,i.lead?`Federführend: ${committeeById(i.lead)?.name}`:'',bodies(i).length?`Gremien: ${bodies(i).join(', ')}`:'',i.originator?`Urheber: ${i.originator}`:'',`Quelle: ${i.url}`,i.pdfUrl?`PDF: ${i.pdfUrl}`:''].filter(Boolean).join('\n');
 const groups=[...new Set(b.items.flatMap(i=>[...i.committees,...i.ministries]))];
 const text=['POLICY MONITOR · TRUMPF · Ausgewählte Ausschüsse und Ressorts',date(b.createdAt,true),b.summary,
 ...groups.flatMap(g=>['\n'+(committeeById(g)?.name??ministryById(g)?.name??g),...b.items.filter(i=>i.committees.includes(g)||i.ministries.includes(g)).map(entry)]),
 ...(b.items.some(i=>!i.committees.length&&!i.ministries.length)?['\nOhne Gremienzuordnung',...b.items.filter(i=>!i.committees.length&&!i.ministries.length).map(entry)]:[])].join('\n\n');
 try{if(navigator.share){await navigator.share({title:'Policy Briefing '+b.day,text});}else{const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`Briefing-${b.day}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(e){if((e as Error).name!=='AbortError')setError('Export fehlgeschlagen.');}}
 async function toggleArchive(item:Item){setBusy(true);try{await request(conn,'items/'+item.id,'PATCH',{archived:!item.archived});await refresh();setSelected({...item,archived:!item.archived});setNotice(item.archived?'Dokument wiederhergestellt.':'Dokument archiviert.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function loadHistory(){setTab('history');try{setVersions(await request(conn,'history/'+selected!.id));}catch(e){setError((e as Error).message);}}
 const lead=selected?.lead?committeeById(selected.lead):undefined;
 return <><Head><title>Policy Monitor · TRUMPF</title><meta name="description" content="Neue Dokumente aus ausgewählten Bundestagsausschüssen und Ressorts"/><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/><meta name="theme-color" content="#1038d4"/></Head>
 <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brandmark"><Radar size={27}/></div><div><strong>TRUMPF</strong><span>PUBLIC POLICY</span></div></div><div className="workspace">MONITORING WORKSPACE</div><nav aria-label="Hauptnavigation">{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>navigate(id)}><Icon size={20}/><span>{label}</span>{view===id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><ShieldCheck size={21}/><div><strong>Amtliche Quellen</strong><span>Anzeigen, nicht bewerten</span></div></div></aside>
 <main ref={mainRef} className="main"><header className="topbar"><div className="mobile-brand"><Radar size={22}/><b>TRUMPF</b><span>Policy Monitor</span></div><div className="breadcrumb">Public Policy <ChevronRight size={14}/> {nav.find(n=>n[0]===view)?.[1]}</div><div className={'connection '+(online?'connected':'')}><span/>{STATIC?(latest?'Stand '+date(latest.createdAt,true):'Kein Stand geladen'):online?'Verbunden':data.items.length?'Gespeicherter Stand':'Noch nicht verbunden'}</div></header>
 <div className="content">{error&&<div className="notice error" role="alert"><AlertCircle size={19}/><span>{error}{HOSTED&&error.includes('anmelden')&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top"> Jetzt anmelden</a>}</span><button aria-label="Meldung schließen" onClick={()=>setError('')}><X size={17}/></button></div>}{notice&&<div className="notice" role="status"><Check size={19}/><span>{notice}</span></div>}
 {selected?<><button className="back" onClick={()=>setSelected(null)}><ArrowLeft size={18}/> Zurück zur Übersicht</button><div className="detail-heading"><div className="eyebrow">{lead?lead.name:selected.institution} · {selected.documentType}</div><h1>{selected.title}</h1><div className="tags"><span className={'badge '+selected.change}>{labels[selected.change]}</span>{selected.documentNumber&&<span className="badge neutral">Drucksache {selected.documentNumber}</span>}{selected.step&&<span className="badge neutral">{selected.step}</span>}{selected.archived&&<span className="badge neutral">Archiviert</span>}</div></div><div className="detail-tabs"><button className={tab==='detail'?'active':''} onClick={()=>setTab('detail')}>Dokument & Quelle</button>{!STATIC&&<button className={tab==='history'?'active':''} onClick={loadHistory}>Versionen & Änderungen</button>}</div>
 {tab==='detail'?<div className="detail-grid"><section className="panel"><div className="eyebrow">DAS PAPIER</div><h2>{selected.documentType}{selected.step&&selected.step!==selected.documentType?` · ${selected.step}`:''}</h2>{selected.text&&<p className="source-text">{selected.text}</p>}<div className="doc-links">{selected.pdfUrl&&<a href={selected.pdfUrl} target="_blank" rel="noopener noreferrer" className="button primary"><FileDown size={17}/>Amtliches PDF öffnen</a>}<a href={selected.url} target="_blank" rel="noopener noreferrer" className="button secondary"><ArrowUpRight size={17}/>{selected.sourceId.startsWith('dip')?'Vorgang im DIP':'Originalquelle'}</a></div><hr/><dl>{[['Drucksachennummer',selected.documentNumber??'Nicht in der Quelle angegeben'],['Verfahrensschritt',selected.step??'Nicht in der Quelle angegeben'],['Vorgangstyp',selected.procedure??'Nicht in der Quelle angegeben'],['Urheber',selected.originator??'Nicht in der Quelle angegeben'],['Veröffentlicht',date(selected.publishedAt)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><span className="muted">Angezeigt werden ausschließlich die Metadaten der amtlichen Quelle. Der Inhalt wird nicht ausgewertet und nicht bewertet.</span></section>
 <aside className="panel"><h2>Gremien</h2>{lead&&<div className="body-block"><span className="badge lead">Federführend</span><strong>{lead.name}</strong><p>{lead.scope}</p></div>}
 {selected.committees.filter(c=>c!==selected.lead).map(c=>{const k=committeeById(c);return k?<div className="body-block" key={c}><span className="badge neutral">Mitberatend</span><strong>{k.name}</strong><p>{k.scope}</p></div>:null;})}
 {selected.ministries.map(m=>{const k=ministryById(m);return k?<div className="body-block" key={m}><span className="badge channel">Ressort</span><strong>{k.name}</strong><p>{k.scope}</p></div>:null;})}
 {!selected.committees.length&&!selected.ministries.length&&<p className="muted">Diese Quelle liefert keine Gremienzuordnung.</p>}
 <hr/><dl>{[['Erstmals erfasst',date(selected.firstSeen,true)],['Zuletzt abgerufen',date(selected.lastSeen,true)],['Version',String(selected.version)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>
 {!STATIC&&<button className="button secondary full" disabled={busy||!online} onClick={()=>toggleArchive(selected)}><Archive size={17}/>{selected.archived?'Wiederherstellen':'Archivieren'}</button>}</aside></div>:
 <section className="panel"><h2>Änderung zur Vorversion</h2>{!versions?<p>Versionsverlauf wird geladen. Bei fehlender Verbindung bitte erneut versuchen.</p>:versions.versions.length<2?<p>Es liegt ein Ausgangsstand vor. Ein Vergleich ist ab der zweiten Version möglich.</p>:<><div className="diff">{versions.diff.map((part,i)=><span key={i} className={part.added?'added':part.removed?'removed':''}>{part.value}</span>)}</div><p className="muted">Grün: hinzugefügt · Rot: entfernt. Verglichen werden Titel, Dokumenttyp, Verfahrensschritt und Drucksachennummer.</p></>}{versions?.versions.map(v=><details key={v.version}><summary>Version {v.version} · {date(v.changedAt,true)}</summary><p>{v.title}</p><p>{v.documentType}{v.step?' · '+v.step:''}{v.documentNumber?' · Drucksache '+v.documentNumber:''}</p><p>Datum: {date(v.publishedAt)}</p><code>SHA-256: {v.hash}</code></details>)}</section>}</>:
 view==='overview'?<><div className="page-heading"><div><div className="eyebrow">AUSGEWÄHLTE AUSSCHÜSSE UND RESSORTS</div><h1>Was neu ist.</h1><p>Neue und geänderte amtliche Dokumente. Mit Quelle, ohne Bewertung.</p></div>{!STATIC&&<button className="button primary" onClick={run} disabled={busy||(!HOSTED&&!conn.token)}><RefreshCw size={17} className={busy?'spin':''}/>{busy?'Prüfung läuft …':'Quellen prüfen'}</button>}</div>
 <section className="briefing-hero"><div className="hero-top"><span className="eyebrow light"><FileText size={15}/> LETZTER QUELLENLAUF</span><span className="hero-time"><Clock size={14}/>{latest?date(latest.createdAt,true):'Noch kein Quellenlauf'}</span></div><h2>{latest?(latest.baseline?'Der Ausgangsstand ist erfasst.':'Die Änderungen im Überblick.'):'Dein Monitoring ist bereit.'}</h2><p>{latest?.summary??'Prüfe die angebundenen amtlichen Quellen. Jedes Dokument erscheint mit Ausschuss, Verfahrensschritt und Link auf das amtliche PDF.'}</p><div className="hero-bottom"><span>{data.sources.filter(s=>s.status==='ok').length} von {data.sources.length} Quellen zuletzt erfolgreich geprüft</span><button onClick={()=>navigate(latest?'briefings':'sources')}>{latest?'Briefing lesen':'Quellen ansehen'} <ArrowUpRight size={18}/></button></div></section>
 <div className="metrics">{([['new','Seit dem letzten Stand hinzugekommen'],['changed','Verfahrensschritt oder Metadaten geändert'],['baseline','Beim Erstimport erfasst']] as [Change,string][]).map(([c,hint])=><button key={c} aria-pressed={status===c} className={'metric '+c+(status===c?' chosen':'')} onClick={()=>setStatus(status===c?'':c)}><div><span className="metric-dot"/>{labels[c]}</div><strong>{counts(c).toString().padStart(2,'0')}</strong><span>{hint}</span></button>)}</div>
 <section className="results"><div className="section-heading"><h2>{showArchive?'Archiv':'Erfasste Dokumente'} <span>{matches.length}</span></h2>{!STATIC&&<button className="text-button" onClick={()=>{setShowArchive(!showArchive);setStatus('');}}><Archive size={16}/>{showArchive?'Aktive Dokumente':'Archiv'}</button>}</div><div className="search-row"><label className="search"><Search size={18}/><input aria-label="Dokumente durchsuchen" placeholder="Titel, Drucksachennummer oder Ausschuss suchen" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="Suche löschen"><X size={16}/></button>}</label><button className={'filter-button '+(filters?'selected':'')} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={18}/><span>Filter</span></button></div>
 {filters&&<div className="filters"><label>Ausschuss oder Ressort<select value={body} onChange={e=>setBody(e.target.value)}><option value="">Alle ausgewählten Gremien</option><optgroup label="Ausschüsse">{COMMITTEES.map(c=><option key={c.id} value={c.id}>{c.short}</option>)}</optgroup><optgroup label="Ressorts">{MINISTRIES.map(m=><option key={m.id} value={m.id}>{m.short}</option>)}</optgroup></select></label><label>Dokumenttyp<select value={docType} onChange={e=>setDocType(e.target.value)}><option value="">Alle Dokumenttypen</option>{types.map(t=><option key={t} value={t}>{t}</option>)}</select></label><label>Quelle<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Alle Quellen</option>{data.sources.map(s=><option key={s.id} value={s.id}>{s.institution} · {s.name}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as Change|'')}><option value="">Alle Status</option>{(['baseline','new','changed','unchanged'] as Change[]).map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label>Veröffentlicht ab<input type="date" value={after} onChange={e=>setAfter(e.target.value)}/></label><button className="text-button" onClick={()=>{setSource('');setBody('');setStatus('');setDocType('');setAfter('');setQuery('');}}>Zurücksetzen</button></div>}
 {body&&<button className="active-filter" onClick={()=>setBody('')}>{committeeById(body)?.short??ministryById(body)?.short} <X size={14}/></button>}
 <div className="item-list">{matches.map(item=><ItemCard key={item.id} item={item} onClick={()=>setSelected(item)}/>)}{!matches.length&&<div className="empty"><Radar size={40}/><h3>{data.items.length?'Keine passenden Dokumente':'Noch kein Quellenstand'}</h3><p>{data.items.length?'Passe die Suche oder Filter an.':'Starte den ersten Quellenlauf, um die amtlichen Veröffentlichungen zu laden.'}</p>{!STATIC&&!HOSTED&&!conn.token&&<button className="button secondary" onClick={()=>navigate('settings')}>Verbindung einrichten</button>}</div>}</div></section><div className="footnote"><ShieldCheck size={16}/><span>Keine Meldung ist kein Entwarnungsnachweis. Die Anzeige gilt ausschließlich für die ausgewählten Gremien und die erfolgreich erfassten Quellen.</span></div></>:
 view==='committees'?<><div className="page-heading"><div><div className="eyebrow">DIE AUSWAHL</div><h1>Ausschüsse & Ressorts.</h1><p>Nur diese Gremien werden überwacht. Alles andere wird verworfen, bevor es in die App kommt.</p></div></div>
 <div className="notice"><ShieldCheck size={20}/><span>Die Auswahl ist die einzige inhaltliche Entscheidung des Systems. Einzelne Dokumente werden danach nicht mehr gewichtet.</span></div>
 {(['Bundestag','Bundesrat'] as const).map(inst=><section className="body-section" key={inst}><h2>{inst}</h2><div className="body-grid">{COMMITTEES.filter(c=>c.institution===inst).map(c=>{const items=activeIn(c.id);return <button className="body-card" key={c.id} onClick={()=>focusBody(c.id)}><div className="body-top"><Landmark size={19}/><strong>{items.length}</strong></div><h3>{c.name}</h3><p>{c.scope}</p><span className="body-foot">{items.filter(i=>i.change==='new'||i.change==='changed').length} neu oder geändert <ChevronRight size={15}/></span></button>;})}</div></section>)}
 <section className="body-section"><h2>Ressorts</h2><div className="body-grid">{MINISTRIES.map(m=>{const items=activeIn(m.id);return <button className="body-card" key={m.id} onClick={()=>focusBody(m.id)}><div className="body-top"><Building2 size={19}/><strong>{items.length}</strong></div><h3>{m.name}</h3><p>{m.scope}</p><span className="body-foot">{items.filter(i=>i.change==='new'||i.change==='changed').length} neu oder geändert <ChevronRight size={15}/></span></button>;})}</div></section></>:
 view==='briefings'?<><div className="page-heading"><div><div className="eyebrow">DOKUMENTIERT & NACHVOLLZIEHBAR</div><h1>Briefings.</h1><p>Gespeicherte Stände mit unveränderlichen Quellenverweisen.</p></div>{briefing&&<button className="button secondary" onClick={()=>exportBriefing(briefing)}><Download size={17}/>Exportieren</button>}</div>{data.briefings.length?<><label className="briefing-select">Briefing auswählen<select value={briefing?.id} onChange={e=>setPickedBriefing(e.target.value)}>{data.briefings.map(b=><option key={b.id} value={b.id}>{date(b.createdAt,true)}{b.baseline?' · Ausgangsstand':''}</option>)}</select></label><section className="panel briefing-summary"><div className="eyebrow">ÜBERBLICK</div><h2>{date(briefing.createdAt)}</h2><p>{briefing.summary}</p><div className="coverage"><span><Check size={15}/>{briefing.coverage.ok} geprüft</span><span><AlertCircle size={15}/>{briefing.coverage.failed} Fehler</span><span><Radio size={15}/>{briefing.coverage.manual} offen</span></div>{briefing.errors.map(e=><p className="warning-text" key={e}>{e}</p>)}</section>
 {[...new Set(briefing.items.flatMap(i=>[...i.committees,...i.ministries]))].map(g=><section className="briefing-group" key={g}><h2>{committeeById(g)?.name??ministryById(g)?.name??g}</h2>{briefing.items.filter(i=>i.committees.includes(g)||i.ministries.includes(g)).map(i=><ItemCard key={i.id} item={i} onClick={()=>setSelected(i)}/>)}</section>)}
 {!briefing.items.length&&<section className="briefing-group"><p className="muted">In diesem Lauf gab es keine neuen oder geänderten Dokumente in den ausgewählten Gremien.</p></section>}
 <section className="panel"><h2><History size={20}/> Änderungslog</h2>{data.events.slice(0,60).map(e=><button className="event" key={e.id} onClick={()=>setSelected(data.items.find(i=>i.id===e.itemId)??null)}><span className="event-mark"/><div><strong>{e.title}</strong><span>{labels[e.change]} · Version {e.version} · {date(e.at,true)}</span></div><ChevronRight size={16}/></button>)}</section></>:<div className="empty panel"><FileText size={40}/><h3>Noch kein Briefing vorhanden</h3><p>Nach einem Quellenlauf erscheint hier der gespeicherte Stand.</p></div>}</>:
 view==='sources'?<><div className="page-heading"><div><div className="eyebrow">TRANSPARENTE ABDECKUNG</div><h1>Die Quellen.</h1><p>Amtliche Veröffentlichungen. Jeder Abruf mit eigenem Status.</p></div>{!STATIC&&<button className="button primary" onClick={run} disabled={busy||(!HOSTED&&!conn.token)}><RefreshCw size={17} className={busy?'spin':''}/>Quellen prüfen</button>}</div><div className="notice"><ShieldCheck size={20}/><span>„Offen“ bedeutet: Diese Quelle wird noch nicht automatisch überwacht.</span></div><div className="source-grid">{data.sources.map(s=><section className="panel source-card" key={s.id}><div className="source-top"><div className="source-symbol"><Radio size={21}/></div><span className={'badge '+(s.status==='ok'?'success':s.status==='error'?'failure':'neutral')}>{s.status==='ok'?'Abruf erfolgreich':s.status==='error'?'Abruf fehlgeschlagen':s.status==='pending'?'Bereit für Erstabruf':s.status==='setup'?'Schlüssel fehlt':'Offen'}</span></div><span className="eyebrow">{s.institution}</span><h2>{s.name}</h2><p>{s.note}</p>{s.error&&<p className="warning-text">{s.error}</p>}<div className="source-meta"><span>{s.checkedAt?date(s.checkedAt,true):'Noch kein erfolgreicher Abruf'}</span>{s.count!==undefined&&<span>{s.count} Einträge im Fenster</span>}</div><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-link">Amtliche Quelle <ArrowUpRight size={16}/></a></section>)}</div></>:
 <><div className="page-heading"><div><div className="eyebrow">DEIN WORKSPACE</div><h1>Einstellungen.</h1><p>Verbindung, Auswahlgrundlage und Betriebsstatus.</p></div></div><div className="settings-grid">{STATIC?<section className="panel"><h2>Täglich aktualisierte Seite</h2><p>Diese Seite braucht keinen Server und keinen Schlüssel. Ein Zeitplan holt jeden Morgen um 06:00 Uhr Berliner Zeit die amtlichen Quellen ab und veröffentlicht den neuen Stand hier. Du öffnest die Seite und liest.</p><div className="action-box"><strong>Als App auf dem Handy</strong><p>Im Browser über „Teilen“ beziehungsweise das Menü „Zum Home-Bildschirm“ wählen. Danach startet die Seite wie eine App, auch ohne Mac.</p></div><p className="muted">Nur lesend: Quellenlauf, Archivieren und der Versionsvergleich brauchen den Server und sind hier ausgeblendet.</p></section>:<section className="panel"><h2>{HOSTED?'Online verbunden':'Monitoring-Server'}</h2><p>Der Server sammelt die Quellen und speichert ihre Versionen. Bereits geladene Stände bleiben auf diesem Gerät verfügbar.</p>{!HOSTED&&<form onSubmit={e=>{e.preventDefault();saveConnection();}}><label>Server-Adresse<input type="url" placeholder="https://monitor.example.org" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label><label>Verbindungsschlüssel<input type="password" autoComplete="off" placeholder="Persönlicher Zugangsschlüssel" value={draft.token} onChange={e=>setDraft({...draft,token:e.target.value})}/></label><button className="button primary" disabled={busy||!ready} type="submit">{busy?'Verbindung wird geprüft …':'Prüfen & speichern'}</button></form>}{HOSTED?<div className="action-box"><strong>Ohne MacBook nutzbar</strong><p>Quellen und Stände werden auf deinem privaten Online-Server gespeichert. Du benötigst nur eine Internetverbindung und deine ChatGPT-Anmeldung.</p><button className="button secondary" onClick={()=>refresh()}>Verbindung prüfen</button></div>:<p className="muted">Lokaler Betrieb: iPhone und Mac müssen denselben Server erreichen können.</p>}</section>}
 <section className="panel"><h2>Betriebsstatus</h2><dl><div><dt>Letzter Datenstand</dt><dd>{data.serverTime?date(data.serverTime,true):'Noch nicht geladen'}</dd></div><div><dt>Morgenlauf · 06:00 Berlin</dt><dd>{STATIC?'Täglich über den veröffentlichten Zeitplan':data.scheduleEnabled?'Serverseitiger Zeitplan als eingerichtet gemeldet':'Zeitplan vorbereitet, noch nicht aktiviert'}</dd></div><div><dt>Überwachte Gremien</dt><dd>{COMMITTEES.length} Ausschüsse, {MINISTRIES.length} Ressorts</dd></div><div><dt>Arbeitsweise</dt><dd>Anzeigen mit Quellenverweis. Keine Relevanzbewertung, keine Priorisierung, keine KI-Zusammenfassung.</dd></div></dl><div className="action-box"><strong>Auswahl statt Bewertung</strong><p>Gefiltert wird ausschließlich über die Zuständigkeit des Gremiums. Was dort eingeht, wird unverändert mit Drucksachennummer und amtlichem PDF angezeigt.</p><button className="button secondary" onClick={()=>navigate('committees')}>Auswahl ansehen</button></div></section></div></>}
 </div><footer className="footer">POLICY MONITOR <span>Public Policy · Persönlicher Prototyp</span></footer></main><nav className="bottom-nav" aria-label="Mobile Navigation">{nav.map(([id,label,Icon])=><button className={view===id?'active':''} key={id} onClick={()=>navigate(id)}><Icon size={21}/><span>{label}</span></button>)}</nav></div></>;
}
function ItemCard({item,onClick}:{item:Item;onClick:()=>void}){
 const lead=item.lead?committeeById(item.lead):undefined;
 return <button className="item-card" onClick={onClick}><div className={'item-stripe '+item.change}/><div className="item-content"><div className="item-meta"><span>{item.documentType}</span>{item.documentNumber&&<><span>·</span><span>Drs. {item.documentNumber}</span></>}<span>·</span><span>{date(item.publishedAt)}</span><span className="change-label">{labels[item.change]}</span></div><h3>{item.title}</h3><div className="tags">{lead&&<span className="badge lead">{lead.short} · federführend</span>}{item.committees.filter(c=>c!==item.lead).map(c=><span className="badge channel" key={c}>{committeeById(c)?.short}</span>)}{item.ministries.map(m=><span className="badge channel" key={m}>{ministryById(m)?.short}</span>)}{item.step&&item.step!==item.documentType&&<span className="badge neutral">{item.step}</span>}{item.pdfUrl&&<span className="badge neutral">PDF</span>}</div></div><ChevronRight className="item-arrow" size={19}/></button>;
}
