import {mkdtempSync,cpSync,symlinkSync,writeFileSync,mkdirSync,rmSync} from 'node:fs';
import {resolve,join} from 'node:path';import {execFileSync} from 'node:child_process';import {tmpdir} from 'node:os';import {build} from 'esbuild';
const root=process.cwd(),stage=mkdtempSync(join(tmpdir(),'policy-cloud-'));
for(const f of ['src','next.config.mjs','tsconfig.json','package.json'])cpSync(join(root,f),join(stage,f),{recursive:true});
mkdirSync(join(stage,'pages'));mkdirSync(join(stage,'public'));for(const f of ['index.tsx','_app.tsx','_document.tsx'])cpSync(join(root,'pages',f),join(stage,'pages',f));
symlinkSync(join(root,'node_modules'),join(stage,'node_modules'),'dir');
execFileSync(process.execPath,[join(root,'node_modules/next/dist/bin/next'),'build','--webpack'],{cwd:stage,env:{...process.env,MOBILE_EXPORT:'1',NEXT_PUBLIC_HOSTED:'1',NEXT_TELEMETRY_DISABLED:'1'},stdio:'inherit'});
rmSync('dist',{recursive:true,force:true});mkdirSync('dist/server',{recursive:true});cpSync(join(stage,'out'),'dist/client',{recursive:true});
await build({entryPoints:['src/worker.ts'],outfile:'dist/server/index.js',bundle:true,format:'esm',platform:'neutral',mainFields:['module','main'],target:'es2022',conditions:['workerd','worker','browser'],external:['node:*','cloudflare:workers'],plugins:[{name:'d1-adapter',setup(b){b.onResolve({filter:/^\.\/db$/},a=>a.importer.endsWith('/src/server/monitor.ts')?{path:resolve('src/server/db-cloud.ts')}:undefined);}}]});
console.log('Cloud Worker und Next.js-Oberfläche erstellt.');
